import type { Researcher } from "@/lib/types";

export const RESEARCHERS: Researcher[] = [
  {
    slug: "hinton",
    name: "Geoffrey Hinton",
    affiliation: "U of Toronto · ex-Google Brain",
    area: ["foundations", "backpropagation", "interpretability"],
    short: "Co-inventor of backpropagation; 2018 Turing Award; 2024 Nobel laureate in Physics for the invention of the Boltzmann machine.",
    bio: "One of the three figures who shaped modern deep learning. Hinton's contributions span backpropagation, the Boltzmann machine, capsule networks, and knowledge distillation. Left Google in 2023 to speak more freely about AI safety.",
    links: [
      { label: "Personal page", href: "https://www.cs.toronto.edu/~hinton/" },
      { label: "Google Scholar", href: "https://scholar.google.com/citations?user=JicYPdAAAAAJ" },
    ],
    keyPapers: [
      { title: "Learning representations by back-propagating errors", year: 1986, url: "https://www.nature.com/articles/323533a0" },
      { title: "Distilling the knowledge in a neural network", year: 2015, url: "https://arxiv.org/abs/1503.02531" },
    ],
  },
  {
    slug: "lecun",
    name: "Yann LeCun",
    affiliation: "Meta AI · NYU",
    area: ["cnn", "self-supervised", "vision-language", "jepa"],
    short: "CNN pioneer; co-Turing-Award; champion of self-supervised learning and JEPA.",
    bio: "Built convolutional networks that became the engine of computer vision. Now leads Meta AI and pushes a vision of learning world models through self-supervised prediction (JEPA).",
    links: [
      { label: "Personal page", href: "https://yann.lecun.com/" },
      { label: "Twitter/X", href: "https://x.com/ylecun" },
    ],
    keyPapers: [
      { title: "Gradient-based learning applied to document recognition", year: 1998, url: "http://yann.lecun.com/exdb/publis/pdf/lecun-98.pdf" },
      { title: "A path towards autonomous machine intelligence", year: 2022, url: "https://openreview.net/forum?id=BZ5a1r-kVsf" },
    ],
  },
  {
    slug: "bengio",
    name: "Yoshua Bengio",
    affiliation: "U of Montreal · MILA · LawZero",
    area: ["foundations", "rnn", "alignment"],
    short: "Co-Turing-Award; founded MILA; 2024 most-cited researcher; AI safety advocate.",
    bio: "Bengio's work on RNNs, attention, and representation learning seeded much of modern NLP. He has shifted toward AI safety, founding LawZero in 2025 to research honest AI.",
    links: [{ label: "MILA", href: "https://mila.quebec/en/yoshua-bengio/" }],
    keyPapers: [
      { title: "Neural machine translation by jointly learning to align and translate", year: 2014, url: "https://arxiv.org/abs/1409.0473" },
    ],
  },
  {
    slug: "ng",
    name: "Andrew Ng",
    affiliation: "Stanford · DeepLearning.AI · AI Fund",
    area: ["education", "applications"],
    short: "Co-founder of Coursera; popularized ML and DL for millions.",
    bio: "Few people have moved more learners into ML than Andrew Ng. His Coursera courses are still many people's first exposure. Now leads DeepLearning.AI and AI Fund.",
    links: [{ label: "Site", href: "https://www.andrewng.org/" }],
    keyPapers: [],
  },
  {
    slug: "karpathy",
    name: "Andrej Karpathy",
    affiliation: "Eureka Labs · ex-OpenAI · ex-Tesla",
    area: ["education", "llm", "vision"],
    short: "Lucid teacher; 'state of GPT' and 'zero-to-hero' lectures defined a generation.",
    bio: "Built ConvNetJS, ran Tesla's vision team, and is now teaching the next wave through Eureka Labs. His video lectures and minGPT/nanoGPT codebases are required reading.",
    links: [
      { label: "Blog", href: "https://karpathy.github.io/" },
      { label: "YouTube", href: "https://www.youtube.com/@AndrejKarpathy" },
    ],
    keyPapers: [],
  },
  {
    slug: "sutskever",
    name: "Ilya Sutskever",
    affiliation: "Safe Superintelligence Inc.",
    area: ["foundations", "transformers", "alignment"],
    short: "Seq2seq, AlexNet, GPT lineage; co-founder OpenAI.",
    bio: "Co-author of AlexNet with Krizhevsky and Hinton; co-invented the seq2seq paradigm; co-founded OpenAI; now founded SSI focused on safe superintelligence.",
    links: [{ label: "SSI", href: "https://ssi.inc" }],
    keyPapers: [
      { title: "Sequence to sequence learning with neural networks", year: 2014, url: "https://arxiv.org/abs/1409.3215" },
      { title: "ImageNet classification with deep CNNs", year: 2012, url: "https://papers.nips.cc/paper/4824-imagenet-classification-with-deep-convolutional-neural-networks" },
    ],
  },
  {
    slug: "hassabis",
    name: "Demis Hassabis",
    affiliation: "Google DeepMind",
    area: ["rl", "agi", "biology"],
    short: "DeepMind co-founder; AlphaGo, AlphaFold; 2024 Nobel Chemistry.",
    bio: "Led DeepMind from chess and Go to protein folding. AlphaGo, AlphaZero, AlphaFold — the through-line is RL plus deep learning at the edge of what's possible.",
    links: [{ label: "DeepMind", href: "https://deepmind.google" }],
    keyPapers: [
      { title: "Mastering the game of Go with deep neural networks and tree search", year: 2016, url: "https://www.nature.com/articles/nature16961" },
    ],
  },
  {
    slug: "fei-fei",
    name: "Fei-Fei Li",
    affiliation: "Stanford · World Labs",
    area: ["vision", "datasets", "policy"],
    short: "Built ImageNet; founder of HAI; visual reasoning and spatial intelligence.",
    bio: "Created ImageNet, the dataset that ignited modern deep learning. Now leads World Labs on spatial intelligence and co-directs Stanford HAI.",
    links: [{ label: "Stanford", href: "https://profiles.stanford.edu/fei-fei-li" }],
    keyPapers: [
      { title: "ImageNet: A large-scale hierarchical image database", year: 2009, url: "https://www.image-net.org/" },
    ],
  },
  {
    slug: "dao",
    name: "Tri Dao",
    affiliation: "Princeton · Together AI",
    area: ["efficiency", "ssm", "attention"],
    short: "FlashAttention; co-author of Mamba & Mamba-2.",
    bio: "Reframed attention as IO-bound and gave us FlashAttention 1/2/3. Co-invented Mamba and is shaping the post-Transformer landscape.",
    links: [{ label: "Site", href: "https://tridao.me/" }],
    keyPapers: [
      { title: "FlashAttention: Fast and memory-efficient exact attention", year: 2022, url: "https://arxiv.org/abs/2205.14135" },
      { title: "Mamba: Linear-time sequence modeling with selective state spaces", year: 2023, url: "https://arxiv.org/abs/2312.00752" },
    ],
  },
  {
    slug: "gu",
    name: "Albert Gu",
    affiliation: "CMU",
    area: ["ssm", "long-context"],
    short: "Architect of S4 and Mamba; structured state-space models.",
    bio: "From HiPPO to S4 to Mamba, Albert Gu's work has consistently pushed structured-state-space architectures forward.",
    links: [{ label: "Site", href: "https://goombalab.github.io/" }],
    keyPapers: [
      { title: "Efficiently modeling long sequences with structured state spaces", year: 2022, url: "https://arxiv.org/abs/2111.00396" },
    ],
  },
  {
    slug: "olah",
    name: "Chris Olah",
    affiliation: "Anthropic",
    area: ["interpretability", "circuits"],
    short: "Pioneer of circuit-level interpretability and visual ML writing.",
    bio: "Founded Distill, then helped seed mech-interp at OpenAI and Anthropic. Anthropic's circuits work and SAEs trace back to his agenda.",
    links: [{ label: "Anthropic", href: "https://transformer-circuits.pub/" }],
    keyPapers: [
      { title: "Zoom in: an introduction to circuits", year: 2020, url: "https://distill.pub/2020/circuits/zoom-in/" },
    ],
  },
  {
    slug: "nanda",
    name: "Neel Nanda",
    affiliation: "Google DeepMind",
    area: ["interpretability", "saes"],
    short: "Mech-interp educator; sparse autoencoder feature work.",
    bio: "Made mech-interp tractable for newcomers through tutorials, and produced foundational empirical work on transformer circuits and SAEs.",
    links: [{ label: "Site", href: "https://www.neelnanda.io/" }],
    keyPapers: [],
  },
  {
    slug: "weng",
    name: "Lilian Weng",
    affiliation: "Thinking Machines Lab",
    area: ["alignment", "writing"],
    short: "Lil'Log: deep, careful surveys of generative models, agents, RLHF.",
    bio: "Her blog is one of the highest-signal references in the field. Topics from diffusion to chain-of-thought to alignment get patient, mathematical treatment.",
    links: [{ label: "Lil'Log", href: "https://lilianweng.github.io/" }],
    keyPapers: [],
  },
  {
    slug: "raschka",
    name: "Sebastian Raschka",
    affiliation: "Lightning AI",
    area: ["education", "applications"],
    short: "Books and posts that demystify modern LLM training.",
    bio: "Author of multiple books on Python ML and LLMs from scratch. His newsletter is a steady source of practical insight.",
    links: [{ label: "Magazine", href: "https://magazine.sebastianraschka.com/" }],
    keyPapers: [],
  },
  {
    slug: "finn",
    name: "Chelsea Finn",
    affiliation: "Stanford · Google",
    area: ["meta-learning", "robotics"],
    short: "MAML; meta-learning and robotic learning.",
    bio: "Pioneered model-agnostic meta-learning and continues to lead in robot learning, embodied agents, and adaptation.",
    links: [{ label: "Stanford", href: "https://ai.stanford.edu/~cbfinn/" }],
    keyPapers: [
      { title: "Model-agnostic meta-learning for fast adaptation of deep networks", year: 2017, url: "https://arxiv.org/abs/1703.03400" },
    ],
  },
  {
    slug: "abbeel",
    name: "Pieter Abbeel",
    affiliation: "UC Berkeley",
    area: ["rl", "robotics"],
    short: "Deep RL & robotic manipulation.",
    bio: "Has shaped a generation of deep RL researchers; founded Covariant; consistently produces foundational work on robot learning.",
    links: [{ label: "Berkeley", href: "https://people.eecs.berkeley.edu/~pabbeel/" }],
    keyPapers: [],
  },
  {
    slug: "levine",
    name: "Sergey Levine",
    affiliation: "UC Berkeley",
    area: ["rl", "offline-rl"],
    short: "Offline RL, decision transformers, robot learning.",
    bio: "His group's work on offline RL, world models, and policy learning is essential reading for anyone working on decision-making with neural networks.",
    links: [{ label: "Berkeley", href: "https://people.eecs.berkeley.edu/~svlevine/" }],
    keyPapers: [],
  },
  {
    slug: "dean",
    name: "Jeff Dean",
    affiliation: "Google DeepMind",
    area: ["systems", "scale"],
    short: "Built much of Google's ML infrastructure.",
    bio: "From MapReduce to TensorFlow to Pathways, Dean's work makes large-scale training possible.",
    links: [{ label: "Google Research", href: "https://research.google/people/jeffdean/" }],
    keyPapers: [],
  },
  {
    slug: "howard",
    name: "Jeremy Howard",
    affiliation: "fast.ai · Answer.AI",
    area: ["education", "applications"],
    short: "fast.ai's top-down teaching; ULMFiT.",
    bio: "Made deep learning accessible to thousands through fast.ai's MOOC. Co-founded Answer.AI to push compute-efficient research.",
    links: [{ label: "fast.ai", href: "https://www.fast.ai/" }],
    keyPapers: [
      { title: "Universal language model fine-tuning for text classification (ULMFiT)", year: 2018, url: "https://arxiv.org/abs/1801.06146" },
    ],
  },
  {
    slug: "vaswani",
    name: "Ashish Vaswani",
    affiliation: "Essential AI · ex-Google Brain",
    area: ["transformers", "nlp"],
    short: "Lead author of 'Attention Is All You Need'.",
    bio: "Co-led the Transformer paper that defined modern AI architecture.",
    links: [],
    keyPapers: [
      { title: "Attention is all you need", year: 2017, url: "https://arxiv.org/abs/1706.03762" },
    ],
  },
  {
    slug: "shazeer",
    name: "Noam Shazeer",
    affiliation: "Character.AI · ex-Google",
    area: ["transformers", "moe"],
    short: "Co-author of Transformer, Switch, MoE seminal work.",
    bio: "From sparsely-gated mixture of experts to the Transformer, Shazeer's contributions are foundational.",
    links: [],
    keyPapers: [
      { title: "Outrageously large neural networks: the sparsely-gated MoE layer", year: 2017, url: "https://arxiv.org/abs/1701.06538" },
    ],
  },
  {
    slug: "radford",
    name: "Alec Radford",
    affiliation: "ex-OpenAI",
    area: ["llm", "clip"],
    short: "GPT-1/2, CLIP, Whisper.",
    bio: "Quietly authored some of the most consequential papers of the era — GPT, CLIP, Whisper.",
    links: [],
    keyPapers: [
      { title: "Learning transferable visual models from natural language supervision (CLIP)", year: 2021, url: "https://arxiv.org/abs/2103.00020" },
    ],
  },
  {
    slug: "brown",
    name: "Tom Brown",
    affiliation: "Anthropic",
    area: ["llm", "scaling"],
    short: "GPT-3 lead author.",
    bio: "Led the GPT-3 paper that demonstrated few-shot in-context learning at scale.",
    links: [],
    keyPapers: [
      { title: "Language models are few-shot learners", year: 2020, url: "https://arxiv.org/abs/2005.14165" },
    ],
  },
  {
    slug: "devlin",
    name: "Jacob Devlin",
    affiliation: "ex-Google",
    area: ["nlp", "encoder"],
    short: "BERT first author.",
    bio: "BERT defined the encoder pre-training era and remains a workhorse for NLP.",
    links: [],
    keyPapers: [
      { title: "BERT: Pre-training of deep bidirectional Transformers", year: 2018, url: "https://arxiv.org/abs/1810.04805" },
    ],
  },
  {
    slug: "kingma",
    name: "Diederik Kingma",
    affiliation: "Anthropic · ex-OpenAI",
    area: ["generative", "optimization"],
    short: "VAEs, Adam, Glow.",
    bio: "Author of the VAE paper, the Adam optimizer, and Glow normalizing flows. A theorist who keeps shipping practical tools.",
    links: [],
    keyPapers: [
      { title: "Auto-encoding variational Bayes", year: 2014, url: "https://arxiv.org/abs/1312.6114" },
      { title: "Adam: a method for stochastic optimization", year: 2015, url: "https://arxiv.org/abs/1412.6980" },
    ],
  },
  {
    slug: "ho",
    name: "Jonathan Ho",
    affiliation: "Google",
    area: ["diffusion"],
    short: "DDPM author.",
    bio: "DDPM made denoising diffusion practical and ignited the modern image-generation wave.",
    links: [],
    keyPapers: [
      { title: "Denoising diffusion probabilistic models", year: 2020, url: "https://arxiv.org/abs/2006.11239" },
    ],
  },
  {
    slug: "rombach",
    name: "Robin Rombach",
    affiliation: "Black Forest Labs",
    area: ["diffusion"],
    short: "Stable Diffusion / Latent Diffusion.",
    bio: "Latent Diffusion Models made diffusion fast and accessible; now leads FLUX at Black Forest Labs.",
    links: [],
    keyPapers: [
      { title: "High-resolution image synthesis with latent diffusion models", year: 2022, url: "https://arxiv.org/abs/2112.10752" },
    ],
  },
  {
    slug: "goodfellow",
    name: "Ian Goodfellow",
    affiliation: "DeepMind · ex-Apple",
    area: ["generative", "security"],
    short: "GAN inventor; 'Deep Learning' textbook co-author.",
    bio: "Invented GANs in 2014; co-authored the standard 'Deep Learning' textbook.",
    links: [],
    keyPapers: [
      { title: "Generative adversarial networks", year: 2014, url: "https://arxiv.org/abs/1406.2661" },
    ],
  },
  {
    slug: "karras",
    name: "Tero Karras",
    affiliation: "NVIDIA",
    area: ["generative", "images"],
    short: "StyleGAN family.",
    bio: "Pushed image GANs to photoreal quality through StyleGAN 1/2/3.",
    links: [],
    keyPapers: [
      { title: "A style-based generator architecture for GANs", year: 2019, url: "https://arxiv.org/abs/1812.04948" },
    ],
  },
  {
    slug: "dinh",
    name: "Laurent Dinh",
    affiliation: "Apple",
    area: ["generative", "flows"],
    short: "Real NVP / coupling flows.",
    bio: "Foundational normalizing flow architectures.",
    links: [],
    keyPapers: [
      { title: "Density estimation using Real NVP", year: 2017, url: "https://arxiv.org/abs/1605.08803" },
    ],
  },
  {
    slug: "sutton",
    name: "Richard Sutton",
    affiliation: "U of Alberta · DeepMind",
    area: ["rl", "foundations"],
    short: "Co-author of the RL textbook; 2024 Turing Award.",
    bio: "Co-author of 'Reinforcement Learning: An Introduction' with Andrew Barto. Awarded the 2024 Turing Award for foundational work in RL.",
    links: [{ label: "Site", href: "http://incompleteideas.net/" }],
    keyPapers: [],
  },
  {
    slug: "barto",
    name: "Andrew Barto",
    affiliation: "UMass Amherst",
    area: ["rl"],
    short: "Co-author RL textbook; 2024 Turing Award.",
    bio: "With Sutton, defined the modern formulation of RL.",
    links: [],
    keyPapers: [],
  },
  {
    slug: "schulman",
    name: "John Schulman",
    affiliation: "Anthropic · ex-OpenAI",
    area: ["rl", "rlhf"],
    short: "TRPO, PPO, RLHF for ChatGPT.",
    bio: "Authored PPO — the workhorse of deep RL — and led RLHF work at OpenAI.",
    links: [],
    keyPapers: [
      { title: "Proximal policy optimization algorithms", year: 2017, url: "https://arxiv.org/abs/1707.06347" },
    ],
  },
  {
    slug: "rafailov",
    name: "Rafael Rafailov",
    affiliation: "Stanford",
    area: ["rlhf", "alignment"],
    short: "DPO author.",
    bio: "Showed RLHF could be replaced by Direct Preference Optimization, simplifying alignment.",
    links: [],
    keyPapers: [
      { title: "Direct preference optimization", year: 2023, url: "https://arxiv.org/abs/2305.18290" },
    ],
  },
  {
    slug: "stiennon",
    name: "Nisan Stiennon",
    affiliation: "OpenAI",
    area: ["rlhf"],
    short: "RLHF for summarization paper.",
    bio: "Lead on the early summarization RLHF work that became the template for InstructGPT and ChatGPT.",
    links: [],
    keyPapers: [
      { title: "Learning to summarize from human feedback", year: 2020, url: "https://arxiv.org/abs/2009.01325" },
    ],
  },
  {
    slug: "silver",
    name: "David Silver",
    affiliation: "Google DeepMind · UCL",
    area: ["rl"],
    short: "AlphaGo / AlphaZero lead.",
    bio: "Architected the AlphaGo and AlphaZero systems that combined search with deep RL.",
    links: [],
    keyPapers: [],
  },
  {
    slug: "vapnik",
    name: "Vladimir Vapnik",
    affiliation: "Columbia",
    area: ["learning-theory"],
    short: "SVM and statistical learning theory.",
    bio: "Vapnik's VC dimension and SVM remain foundational to learning theory.",
    links: [],
    keyPapers: [],
  },
  {
    slug: "scholkopf",
    name: "Bernhard Schölkopf",
    affiliation: "Max Planck Tübingen",
    area: ["kernels", "causality"],
    short: "Kernel methods and causal ML.",
    bio: "Authored 'Learning with Kernels'; pioneered causal inference for machine learning.",
    links: [],
    keyPapers: [],
  },
  {
    slug: "breiman",
    name: "Leo Breiman",
    affiliation: "ex-UC Berkeley",
    area: ["classical-ml"],
    short: "Random forests; bagging.",
    bio: "Random Forests, CART, bagging, and the 'two cultures' essay shaped statistical ML.",
    links: [],
    keyPapers: [],
  },
  {
    slug: "freund",
    name: "Yoav Freund",
    affiliation: "UC San Diego",
    area: ["boosting"],
    short: "AdaBoost co-author.",
    bio: "Co-invented AdaBoost with Robert Schapire — the boosting paradigm.",
    links: [],
    keyPapers: [],
  },
  {
    slug: "chen",
    name: "Tianqi Chen",
    affiliation: "CMU · OctoML",
    area: ["systems", "boosting"],
    short: "XGBoost; TVM; MLC.",
    bio: "Authored XGBoost, TVM, MXNet, and MLC LLM — connective tissue of ML systems.",
    links: [],
    keyPapers: [
      { title: "XGBoost: a scalable tree boosting system", year: 2016, url: "https://arxiv.org/abs/1603.02754" },
    ],
  },
  {
    slug: "mackay",
    name: "David MacKay",
    affiliation: "ex-Cambridge",
    area: ["foundations", "information"],
    short: "Information theory and Bayesian methods.",
    bio: "Author of 'Information Theory, Inference, and Learning Algorithms', a free book that taught a generation.",
    links: [],
    keyPapers: [],
  },
  {
    slug: "strang",
    name: "Gilbert Strang",
    affiliation: "MIT",
    area: ["math"],
    short: "MIT linear algebra; the lectures.",
    bio: "Generations have learned linear algebra from Strang's lectures and textbooks.",
    links: [{ label: "MIT OCW", href: "https://ocw.mit.edu/courses/18-06-linear-algebra-spring-2010/" }],
    keyPapers: [],
  },
  {
    slug: "ruder",
    name: "Sebastian Ruder",
    affiliation: "Cohere",
    area: ["nlp", "optimization"],
    short: "Optimization survey; multilingual NLP.",
    bio: "His optimization survey is a standard reference; pushes multilingual and low-resource NLP.",
    links: [{ label: "Blog", href: "https://www.ruder.io/" }],
    keyPapers: [],
  },
  {
    slug: "kaplan",
    name: "Jared Kaplan",
    affiliation: "Anthropic",
    area: ["scaling", "physics"],
    short: "Original scaling laws paper.",
    bio: "Brought a physicist's perspective to LLMs and authored the original scaling-laws paper.",
    links: [],
    keyPapers: [
      { title: "Scaling laws for neural language models", year: 2020, url: "https://arxiv.org/abs/2001.08361" },
    ],
  },
  {
    slug: "hoffmann",
    name: "Jordan Hoffmann",
    affiliation: "Google DeepMind",
    area: ["scaling"],
    short: "Chinchilla scaling laws.",
    bio: "Lead author of the Chinchilla paper that revised scaling-law conclusions and reshaped training budgets.",
    links: [],
    keyPapers: [
      { title: "Training compute-optimal large language models (Chinchilla)", year: 2022, url: "https://arxiv.org/abs/2203.15556" },
    ],
  },
  {
    slug: "wei",
    name: "Jason Wei",
    affiliation: "OpenAI",
    area: ["llm", "emergence"],
    short: "Chain-of-thought; emergent abilities; FLAN.",
    bio: "Coined and characterized chain-of-thought, emergent abilities, and instruction tuning at scale.",
    links: [],
    keyPapers: [
      { title: "Chain-of-thought prompting elicits reasoning", year: 2022, url: "https://arxiv.org/abs/2201.11903" },
      { title: "Emergent abilities of large language models", year: 2022, url: "https://arxiv.org/abs/2206.07682" },
    ],
  },
  {
    slug: "amodei",
    name: "Dario Amodei",
    affiliation: "Anthropic",
    area: ["safety", "alignment"],
    short: "Anthropic CEO; alignment research direction.",
    bio: "Anthropic CEO. The lab's research agenda — interpretability, RLHF, constitutional AI — bears his fingerprints.",
    links: [{ label: "Anthropic", href: "https://www.anthropic.com" }],
    keyPapers: [],
  },
  {
    slug: "hochreiter",
    name: "Sepp Hochreiter",
    affiliation: "JKU Linz",
    area: ["sequence-models"],
    short: "Co-inventor of LSTMs.",
    bio: "His MSc thesis identified the vanishing gradient problem; LSTM was the answer.",
    links: [],
    keyPapers: [
      { title: "Long short-term memory", year: 1997, url: "https://www.bioinf.jku.at/publications/older/2604.pdf" },
    ],
  },
  {
    slug: "he",
    name: "Kaiming He",
    affiliation: "MIT · ex-Meta",
    area: ["vision"],
    show: true,
    short: "ResNet; MAE; Faster R-CNN.",
    bio: "Authored some of the most-cited vision papers of the decade — ResNet, Faster R-CNN, MAE.",
    links: [],
    keyPapers: [
      { title: "Deep residual learning for image recognition (ResNet)", year: 2016, url: "https://arxiv.org/abs/1512.03385" },
    ],
  } as Researcher,
  {
    slug: "maaten",
    name: "Laurens van der Maaten",
    affiliation: "Meta",
    area: ["visualization", "generative"],
    short: "Author of t-SNE; visualization research at Meta.",
    bio: "Authored t-SNE and influential visualization tooling; works on AI research at Meta.",
    links: [],
    keyPapers: [
      { title: "Visualizing data using t-SNE", year: 2008, url: "https://www.jmlr.org/papers/volume9/vandermaaten08a/vandermaaten08a.pdf" },
    ],
  },
  {
    slug: "mcinnes",
    name: "Leland McInnes",
    affiliation: "Tutte Institute",
    area: ["visualization"],
    short: "UMAP author.",
    bio: "UMAP and HDBSCAN have become standard tools for embedding visualization.",
    links: [],
    keyPapers: [
      { title: "UMAP: Uniform manifold approximation and projection", year: 2018, url: "https://arxiv.org/abs/1802.03426" },
    ],
  },
  {
    slug: "rajbhandari",
    name: "Samyam Rajbhandari",
    affiliation: "Microsoft",
    area: ["systems"],
    short: "ZeRO / DeepSpeed.",
    bio: "Author of ZeRO, the memory-optimization technique behind DeepSpeed.",
    links: [],
    keyPapers: [
      { title: "ZeRO: Memory optimizations toward training trillion-parameter models", year: 2020, url: "https://arxiv.org/abs/1910.02054" },
    ],
  },
  {
    slug: "shoeybi",
    name: "Mohammad Shoeybi",
    affiliation: "NVIDIA",
    area: ["systems"],
    short: "Megatron-LM; tensor parallelism.",
    bio: "Megatron-LM and tensor parallelism opened the door to billion-parameter training.",
    links: [],
    keyPapers: [
      { title: "Megatron-LM: training multi-billion parameter language models", year: 2019, url: "https://arxiv.org/abs/1909.08053" },
    ],
  },
  {
    slug: "hu",
    name: "Edward Hu",
    affiliation: "Microsoft",
    area: ["peft"],
    short: "LoRA author.",
    bio: "LoRA reframed fine-tuning as low-rank updates and unlocked cheap LLM customization.",
    links: [],
    keyPapers: [
      { title: "LoRA: Low-rank adaptation of large language models", year: 2021, url: "https://arxiv.org/abs/2106.09685" },
    ],
  },
  {
    slug: "dettmers",
    name: "Tim Dettmers",
    affiliation: "Allen AI",
    area: ["quantization", "peft"],
    short: "QLoRA; bitsandbytes.",
    bio: "QLoRA, NF4, bitsandbytes — Dettmers' quantization work makes large model training accessible.",
    links: [],
    keyPapers: [
      { title: "QLoRA: efficient finetuning of quantized LLMs", year: 2023, url: "https://arxiv.org/abs/2305.14314" },
    ],
  },
  {
    slug: "frantar",
    name: "Elias Frantar",
    affiliation: "ISTA",
    area: ["quantization"],
    short: "GPTQ author.",
    bio: "GPTQ and SparseGPT brought principled post-training quantization and pruning to LLMs.",
    links: [],
    keyPapers: [
      { title: "GPTQ: Accurate post-training quantization for generative pre-trained Transformers", year: 2023, url: "https://arxiv.org/abs/2210.17323" },
    ],
  },
  {
    slug: "kwon",
    name: "Woosuk Kwon",
    affiliation: "UC Berkeley",
    area: ["systems"],
    short: "vLLM and PagedAttention.",
    bio: "vLLM and PagedAttention reshaped LLM serving by treating KV cache like virtual memory.",
    links: [],
    keyPapers: [
      { title: "Efficient memory management for LLM serving with PagedAttention", year: 2023, url: "https://arxiv.org/abs/2309.06180" },
    ],
  },
  {
    slug: "lewis-switch",
    name: "Mike Lewis",
    affiliation: "FAIR",
    area: ["nlp", "moe"],
    short: "BART, RAG, sparse Transformers.",
    bio: "Author of BART, RAG, and seminal sparse-transformer work.",
    links: [],
    keyPapers: [
      { title: "BART", year: 2019, url: "https://arxiv.org/abs/1910.13461" },
    ],
  },
  {
    slug: "lewis-rag",
    name: "Patrick Lewis",
    affiliation: "Cohere",
    area: ["nlp", "rag"],
    short: "RAG paper lead.",
    bio: "Lead author of the original RAG paper that combined retrieval with sequence-to-sequence generation.",
    links: [],
    keyPapers: [
      { title: "Retrieval-augmented generation for knowledge-intensive NLP tasks", year: 2020, url: "https://arxiv.org/abs/2005.11401" },
    ],
  },
  {
    slug: "belkin",
    name: "Mikhail Belkin",
    affiliation: "UCSD",
    area: ["learning-theory"],
    short: "Double descent.",
    bio: "His work on double descent and benign overfitting reshaped how we think about generalization.",
    links: [],
    keyPapers: [
      { title: "Reconciling modern machine-learning practice and the classical bias-variance trade-off", year: 2019, url: "https://arxiv.org/abs/1812.11118" },
    ],
  },
  {
    slug: "jacot",
    name: "Arthur Jacot",
    affiliation: "NYU · ex-EPFL",
    area: ["theory"],
    short: "Neural Tangent Kernels.",
    bio: "Introduced the NTK framework that opened a clean theoretical lens on training dynamics.",
    links: [],
    keyPapers: [
      { title: "Neural tangent kernel: convergence and generalization in neural networks", year: 2018, url: "https://arxiv.org/abs/1806.07572" },
    ],
  },
  {
    slug: "poli",
    name: "Stefano Poli",
    affiliation: "Stanford · Together AI",
    area: ["sequence-models"],
    short: "Hyena Hierarchy.",
    bio: "Co-author of Hyena, an implicit-convolution alternative to attention.",
    links: [],
    keyPapers: [
      { title: "Hyena Hierarchy: towards larger convolutional language models", year: 2023, url: "https://arxiv.org/abs/2302.10866" },
    ],
  },
  {
    slug: "bronstein",
    name: "Michael Bronstein",
    affiliation: "Oxford",
    area: ["geometric-dl"],
    short: "Geometric deep learning.",
    bio: "Co-author of the 'Grids, Groups, Graphs, Geodesics, and Gauges' synthesis of geometric DL.",
    links: [],
    keyPapers: [
      { title: "Geometric deep learning", year: 2021, url: "https://arxiv.org/abs/2104.13478" },
    ],
  },
  {
    slug: "welling",
    name: "Max Welling",
    affiliation: "U of Amsterdam · CuspAI",
    area: ["generative", "graph"],
    short: "Graph convolutional networks; VAE.",
    bio: "Coauthored VAE with Kingma; pioneered graph convolutional networks.",
    links: [],
    keyPapers: [
      { title: "Semi-supervised classification with graph convolutional networks", year: 2017, url: "https://arxiv.org/abs/1609.02907" },
    ],
  },
  {
    slug: "chen-node",
    name: "Ricky T. Q. Chen",
    affiliation: "Meta FAIR",
    area: ["generative", "ode"],
    short: "Neural ODE author.",
    bio: "Authored Neural Ordinary Differential Equations; works on flow matching at FAIR.",
    links: [],
    keyPapers: [
      { title: "Neural ordinary differential equations", year: 2018, url: "https://arxiv.org/abs/1806.07366" },
    ],
  },
  {
    slug: "assran",
    name: "Mahmoud Assran",
    affiliation: "Meta FAIR",
    area: ["ssl", "vision"],
    short: "I-JEPA / V-JEPA author.",
    bio: "Lead on I-JEPA and V-JEPA, realizing LeCun's vision of representation-prediction SSL.",
    links: [],
    keyPapers: [
      { title: "Self-supervised learning from images with a JEPA", year: 2023, url: "https://arxiv.org/abs/2301.08243" },
    ],
  },
  {
    slug: "liu-llava",
    name: "Haotian Liu",
    affiliation: "U of Wisconsin–Madison",
    area: ["vlm"],
    short: "LLaVA author.",
    bio: "LLaVA showed how to bolt a vision encoder onto an LLM and produce a strong VLM with little compute.",
    links: [],
    keyPapers: [
      { title: "Visual instruction tuning (LLaVA)", year: 2023, url: "https://arxiv.org/abs/2304.08485" },
    ],
  },
  {
    slug: "liphardt",
    name: "Yaron Lipman",
    affiliation: "Weizmann · Meta",
    area: ["generative"],
    short: "Flow matching.",
    bio: "Flow matching is one of the most influential alternatives to diffusion since 2022.",
    links: [],
    keyPapers: [
      { title: "Flow matching for generative modeling", year: 2022, url: "https://arxiv.org/abs/2210.02747" },
    ],
  },
  {
    slug: "liu-rectified",
    name: "Xingchao Liu",
    affiliation: "UT Austin",
    area: ["generative"],
    short: "Rectified flow.",
    bio: "Rectified flow straightens trajectories, enabling 1-NFE generation in many settings.",
    links: [],
    keyPapers: [
      { title: "Flow straight and fast: learning to generate and transfer data with rectified flow", year: 2023, url: "https://arxiv.org/abs/2209.03003" },
    ],
  },
];

export const RESEARCHER_BY_SLUG: Record<string, Researcher> = Object.fromEntries(
  RESEARCHERS.map((r) => [r.slug, r])
);
