import type { ExternalResource } from "@/lib/types";

/** Curated reading lists shown on /resources. Indexed by category. */
export const RESOURCES: Record<string, ExternalResource[]> = {
  "Foundational textbooks": [
    { kind: "book", title: "Deep Learning", source: "Goodfellow, Bengio, Courville", url: "https://www.deeplearningbook.org/", notes: "The textbook." },
    { kind: "book", title: "Reinforcement Learning: An Introduction", source: "Sutton & Barto", url: "http://incompleteideas.net/book/the-book-2nd.html" },
    { kind: "book", title: "Information Theory, Inference, and Learning Algorithms", source: "MacKay", url: "https://www.inference.org.uk/mackay/itila/" },
    { kind: "book", title: "Pattern Recognition and Machine Learning", source: "Bishop", url: "https://www.microsoft.com/en-us/research/uploads/prod/2006/01/Bishop-Pattern-Recognition-and-Machine-Learning-2006.pdf" },
    { kind: "book", title: "Probabilistic Machine Learning (1 & 2)", source: "Kevin Murphy", url: "https://probml.github.io/pml-book/" },
    { kind: "book", title: "Mathematics for Machine Learning", source: "Deisenroth, Faisal, Ong", url: "https://mml-book.github.io/" },
    { kind: "book", title: "Designing Machine Learning Systems", source: "Chip Huyen", url: "https://www.oreilly.com/library/view/designing-machine-learning/9781098107956/" },
    { kind: "book", title: "AI Engineering", source: "Chip Huyen", url: "https://www.oreilly.com/library/view/ai-engineering/9781098166298/" },
    { kind: "book", title: "Build a Large Language Model (From Scratch)", source: "Sebastian Raschka", url: "https://www.manning.com/books/build-a-large-language-model-from-scratch" },
    { kind: "book", title: "Probabilistic Graphical Models", source: "Koller & Friedman", url: "https://mitpress.mit.edu/9780262013192/probabilistic-graphical-models/" },
  ],
  "Free courses": [
    { kind: "course", title: "MIT 18.06 Linear Algebra", source: "Gilbert Strang", url: "https://ocw.mit.edu/courses/18-06-linear-algebra-spring-2010/" },
    { kind: "course", title: "Stanford CS229 Machine Learning", source: "Andrew Ng", url: "https://cs229.stanford.edu/" },
    { kind: "course", title: "Stanford CS231N Deep Learning for Vision", url: "http://cs231n.stanford.edu/" },
    { kind: "course", title: "Stanford CS224N NLP with Deep Learning", url: "https://web.stanford.edu/class/cs224n/" },
    { kind: "course", title: "Stanford CS336 Language Models from Scratch", url: "https://stanford-cs336.github.io/" },
    { kind: "course", title: "Stanford CS25 Transformers United", url: "https://web.stanford.edu/class/cs25/" },
    { kind: "course", title: "fast.ai Practical Deep Learning", source: "Jeremy Howard", url: "https://course.fast.ai/" },
    { kind: "course", title: "Karpathy Neural Networks: Zero to Hero", source: "Andrej Karpathy", url: "https://karpathy.ai/zero-to-hero.html" },
    { kind: "course", title: "Hugging Face NLP Course", url: "https://huggingface.co/learn/nlp-course" },
    { kind: "course", title: "Hugging Face Diffusion Models Course", url: "https://huggingface.co/learn/diffusion-course" },
    { kind: "course", title: "DeepMind x UCL Reinforcement Learning", url: "https://www.deepmind.com/learning-resources/reinforcement-learning-lecture-series-2021" },
    { kind: "course", title: "ARENA: Alignment Research Engineer Accelerator", url: "https://www.arena.education/" },
    { kind: "course", title: "MIT 6.S191 Intro to Deep Learning", url: "http://introtodeeplearning.com/" },
    { kind: "course", title: "Spinning Up in Deep RL (OpenAI)", url: "https://spinningup.openai.com/" },
  ],
  "Essential blogs": [
    { kind: "blog", title: "Distill.pub", url: "https://distill.pub", notes: "Interactive ML articles, gold standard." },
    { kind: "blog", title: "Lil'Log", source: "Lilian Weng", url: "https://lilianweng.github.io/" },
    { kind: "blog", title: "Anthropic Transformer Circuits", url: "https://transformer-circuits.pub/" },
    { kind: "blog", title: "Jay Alammar — The Illustrated Transformer", url: "https://jalammar.github.io/illustrated-transformer/" },
    { kind: "blog", title: "Karpathy's blog", url: "https://karpathy.github.io/" },
    { kind: "blog", title: "Sebastian Raschka magazine", url: "https://magazine.sebastianraschka.com/" },
    { kind: "blog", title: "Sebastian Ruder", url: "https://www.ruder.io/" },
    { kind: "blog", title: "Chip Huyen", url: "https://huyenchip.com/blog/" },
    { kind: "blog", title: "Eugene Yan", url: "https://eugeneyan.com/" },
    { kind: "blog", title: "Simon Willison", url: "https://simonwillison.net/" },
    { kind: "blog", title: "Gradient Updates (Anthropic eng blog)", url: "https://www.anthropic.com/research" },
  ],
  "Podcasts": [
    { kind: "video", title: "Lex Fridman Podcast", url: "https://lexfridman.com/podcast/", notes: "Long-form interviews with AI/ML pioneers." },
    { kind: "video", title: "Latent Space (swyx & Alessio)", url: "https://www.latent.space/podcast" },
    { kind: "video", title: "No Priors (Sarah Guo, Elad Gil)", url: "https://www.no-priors.com/" },
    { kind: "video", title: "Dwarkesh Podcast", url: "https://www.dwarkesh.com/" },
    { kind: "video", title: "The Gradient Podcast", url: "https://thegradientpub.substack.com/s/podcast" },
    { kind: "video", title: "Practical AI", url: "https://practicalai.fm/" },
    { kind: "video", title: "Eye on AI (Craig Smith)", url: "https://www.eye-on.ai/" },
    { kind: "video", title: "Machine Learning Street Talk", url: "https://www.youtube.com/@MachineLearningStreetTalk" },
    { kind: "video", title: "TWIML AI Podcast", url: "https://twimlai.com/podcast/" },
  ],
  "Newsletters": [
    { kind: "blog", title: "The Batch (DeepLearning.AI)", source: "Andrew Ng", url: "https://www.deeplearning.ai/the-batch/" },
    { kind: "blog", title: "Import AI (Jack Clark)", url: "https://importai.substack.com/" },
    { kind: "blog", title: "Last Week in AI", url: "https://lastweekin.ai/" },
    { kind: "blog", title: "AlphaSignal", url: "https://alphasignal.ai/" },
    { kind: "blog", title: "Sequoia AI Atlas", url: "https://www.sequoiacap.com/atlas/" },
    { kind: "blog", title: "Data Science Weekly", url: "https://www.datascienceweekly.org/" },
    { kind: "blog", title: "Ahead of AI (Sebastian Raschka)", url: "https://magazine.sebastianraschka.com/" },
    { kind: "blog", title: "Interconnects (Nathan Lambert)", url: "https://www.interconnects.ai/" },
    { kind: "blog", title: "Deep (Learning) Focus (Cameron Wolfe)", url: "https://cameronrwolfe.substack.com/" },
  ],
  "YouTube channels": [
    { kind: "video", title: "3Blue1Brown", url: "https://www.youtube.com/@3blue1brown", notes: "Visual math intuition (incl. neural-net series)." },
    { kind: "video", title: "Yannic Kilcher", url: "https://www.youtube.com/@YannicKilcher" },
    { kind: "video", title: "AI Coffee Break with Letitia", url: "https://www.youtube.com/@AICoffeeBreak" },
    { kind: "video", title: "Two Minute Papers", url: "https://www.youtube.com/@TwoMinutePapers" },
    { kind: "video", title: "Welch Labs", url: "https://www.youtube.com/@WelchLabsVideo" },
    { kind: "video", title: "StatQuest with Josh Starmer", url: "https://www.youtube.com/@statquest" },
    { kind: "video", title: "Andrej Karpathy", url: "https://www.youtube.com/@AndrejKarpathy" },
    { kind: "video", title: "DeepLearningAI", url: "https://www.youtube.com/@Deeplearningai" },
    { kind: "video", title: "Computerphile", url: "https://www.youtube.com/@Computerphile" },
  ],
  "Conferences": [
    { kind: "doc", title: "NeurIPS — Neural Information Processing Systems", url: "https://neurips.cc/" },
    { kind: "doc", title: "ICML — International Conference on Machine Learning", url: "https://icml.cc/" },
    { kind: "doc", title: "ICLR — International Conference on Learning Representations", url: "https://iclr.cc/" },
    { kind: "doc", title: "ACL — Association for Computational Linguistics", url: "https://www.aclweb.org/" },
    { kind: "doc", title: "EMNLP — Empirical Methods in NLP", url: "https://2024.emnlp.org/" },
    { kind: "doc", title: "COLM — Conference on Language Modeling", url: "https://colmweb.org/" },
    { kind: "doc", title: "CVPR — Computer Vision and Pattern Recognition", url: "https://cvpr.thecvf.com/" },
    { kind: "doc", title: "ICCV / ECCV — Computer Vision conferences", url: "https://iccv2025.thecvf.com/" },
    { kind: "doc", title: "OpenReview", url: "https://openreview.net/", notes: "Open peer review for most ML conferences." },
  ],
  "Hugging Face starting points": [
    { kind: "model", title: "google-bert/bert-base-uncased", url: "https://huggingface.co/google-bert/bert-base-uncased" },
    { kind: "model", title: "openai-community/gpt2", url: "https://huggingface.co/openai-community/gpt2" },
    { kind: "model", title: "meta-llama/Llama-3.2-1B", url: "https://huggingface.co/meta-llama/Llama-3.2-1B" },
    { kind: "model", title: "openai/clip-vit-base-patch32", url: "https://huggingface.co/openai/clip-vit-base-patch32" },
    { kind: "model", title: "stabilityai/stable-diffusion-3.5-medium", url: "https://huggingface.co/stabilityai/stable-diffusion-3.5-medium" },
    { kind: "model", title: "deepseek-ai/DeepSeek-R1", url: "https://huggingface.co/deepseek-ai/DeepSeek-R1" },
    { kind: "model", title: "state-spaces/mamba-2.8b-hf", url: "https://huggingface.co/state-spaces/mamba-2.8b-hf" },
    { kind: "model", title: "mistralai/Mixtral-8x7B-Instruct-v0.1", url: "https://huggingface.co/mistralai/Mixtral-8x7B-Instruct-v0.1" },
    { kind: "model", title: "Qwen/Qwen2.5-7B-Instruct", url: "https://huggingface.co/Qwen/Qwen2.5-7B-Instruct" },
    { kind: "library", title: "transformers", url: "https://github.com/huggingface/transformers" },
    { kind: "library", title: "diffusers", url: "https://github.com/huggingface/diffusers" },
    { kind: "library", title: "peft", url: "https://github.com/huggingface/peft" },
    { kind: "library", title: "trl", url: "https://github.com/huggingface/trl" },
    { kind: "library", title: "datasets", url: "https://github.com/huggingface/datasets" },
    { kind: "library", title: "accelerate", url: "https://github.com/huggingface/accelerate" },
  ],
  "Datasets to know": [
    { kind: "dataset", title: "ImageNet", source: "Fei-Fei Li et al.", url: "https://www.image-net.org/", notes: "The dataset that ignited deep learning." },
    { kind: "dataset", title: "The Pile", source: "EleutherAI", url: "https://pile.eleuther.ai/" },
    { kind: "dataset", title: "RedPajama-Data v2", source: "Together AI", url: "https://www.together.ai/blog/redpajama-data-v2" },
    { kind: "dataset", title: "FineWeb / FineWeb-Edu", source: "Hugging Face", url: "https://huggingface.co/datasets/HuggingFaceFW/fineweb" },
    { kind: "dataset", title: "RefinedWeb", source: "TII", url: "https://huggingface.co/datasets/tiiuae/falcon-refinedweb" },
    { kind: "dataset", title: "LAION-5B", url: "https://laion.ai/blog/laion-5b/" },
    { kind: "dataset", title: "C4 (Colossal Clean Crawled Corpus)", url: "https://huggingface.co/datasets/allenai/c4" },
    { kind: "dataset", title: "OpenWebMath", url: "https://huggingface.co/datasets/open-web-math/open-web-math" },
    { kind: "dataset", title: "MMLU", url: "https://huggingface.co/datasets/cais/mmlu" },
    { kind: "dataset", title: "HumanEval", url: "https://github.com/openai/human-eval" },
    { kind: "dataset", title: "GSM8K", url: "https://huggingface.co/datasets/openai/gsm8k" },
  ],
  "Frontier papers (2024–2026)": [
    { kind: "paper", title: "DeepSeek-R1: Incentivizing reasoning capability in LLMs via RL", url: "https://arxiv.org/abs/2501.12948" },
    { kind: "paper", title: "DeepSeek-V3 technical report", url: "https://arxiv.org/abs/2412.19437" },
    { kind: "paper", title: "DeepSeek-V3.1 technical report", url: "https://arxiv.org/abs/2503.06120" },
    { kind: "paper", title: "OpenAI o1 system card", url: "https://openai.com/index/openai-o1-system-card/" },
    { kind: "paper", title: "OpenAI o3 / o3-mini system card", url: "https://openai.com/index/o3-mini-system-card/" },
    { kind: "paper", title: "Gemini 2.5 technical report", url: "https://blog.google/technology/google-deepmind/gemini-model-thinking-updates-march-2025/" },
    { kind: "paper", title: "Claude 4 / Claude 4.5 system card", url: "https://www.anthropic.com/news/claude-4" },
    { kind: "paper", title: "Llama 3.1 herd of models", url: "https://arxiv.org/abs/2407.21783" },
    { kind: "paper", title: "Mamba-2: Transformers are SSMs", url: "https://arxiv.org/abs/2405.21060" },
    { kind: "paper", title: "FlashAttention-3", url: "https://tridao.me/publications/flash3/flash3.pdf" },
    { kind: "paper", title: "V-JEPA 2 (Meta FAIR)", url: "https://ai.meta.com/research/publications/v-jepa-2-self-supervised-video-models/" },
    { kind: "paper", title: "NVIDIA Nemotron-4 340B", url: "https://arxiv.org/abs/2406.11704" },
    { kind: "paper", title: "Direct Preference Optimization (DPO)", url: "https://arxiv.org/abs/2305.18290" },
    { kind: "paper", title: "GRPO from DeepSeekMath", url: "https://arxiv.org/abs/2402.03300" },
    { kind: "paper", title: "Sparse autoencoders find highly interpretable directions", url: "https://transformer-circuits.pub/2024/scaling-monosemanticity/" },
    { kind: "paper", title: "Flow matching for generative modeling", url: "https://arxiv.org/abs/2210.02747" },
    { kind: "paper", title: "Self-supervised learning from images with a JEPA", url: "https://arxiv.org/abs/2301.08243" },
    { kind: "paper", title: "Test-time scaling: scaling LLM test-time compute optimally", url: "https://arxiv.org/abs/2408.03314" },
  ],
  "Code tutorials & repos": [
    { kind: "library", title: "nanoGPT (Karpathy)", url: "https://github.com/karpathy/nanoGPT", notes: "The minimal GPT implementation everyone reads." },
    { kind: "library", title: "minGPT (Karpathy)", url: "https://github.com/karpathy/minGPT" },
    { kind: "library", title: "llm.c (Karpathy)", url: "https://github.com/karpathy/llm.c" },
    { kind: "library", title: "nanoMoE (lucidrains)", url: "https://github.com/lucidrains/mixture-of-experts" },
    { kind: "library", title: "TransformerLens (Neel Nanda)", url: "https://github.com/TransformerLensOrg/TransformerLens" },
    { kind: "library", title: "torchtitan (PyTorch)", url: "https://github.com/pytorch/torchtitan" },
    { kind: "library", title: "vLLM", url: "https://github.com/vllm-project/vllm" },
    { kind: "library", title: "unsloth (fast LoRA)", url: "https://github.com/unslothai/unsloth" },
    { kind: "library", title: "axolotl (training framework)", url: "https://github.com/axolotl-ai-cloud/axolotl" },
  ],
  "Tools & playgrounds": [
    { kind: "doc", title: "TensorFlow Playground", url: "https://playground.tensorflow.org/" },
    { kind: "doc", title: "Bbycroft LLM Visualizer", url: "https://bbycroft.net/llm" },
    { kind: "doc", title: "Neuronpedia (SAE features)", url: "https://www.neuronpedia.org/" },
    { kind: "doc", title: "OpenAI Tokenizer", url: "https://platform.openai.com/tokenizer" },
    { kind: "doc", title: "Tiktokenizer", url: "https://tiktokenizer.vercel.app/" },
    { kind: "doc", title: "Poloclub CNN Explainer", url: "https://poloclub.github.io/cnn-explainer/" },
    { kind: "doc", title: "Distill: Building Blocks of Interpretability", url: "https://distill.pub/2018/building-blocks/" },
  ],
};
