/**
 * Chronological timeline of ML/AI from 1943 to 2026.
 *
 * Source-of-truth data file for /timeline. Cross-links into existing
 * curriculum topics and researcher records — slugs here MUST exist in
 * `content/curriculum.ts` (TOPICS) and `content/researchers.ts`.
 */

export type Era = {
  slug: string;
  title: string;
  yearRange: [number, number];
  short: string;
  blurb: string;
  hue: string;
  themes: string[];
};

export type EventKind =
  | "paper"
  | "model"
  | "milestone"
  | "system"
  | "controversy"
  | "company";

export type TimelineEvent = {
  id: string;
  year: number;
  month?: number;
  era: string;
  kind: EventKind;
  title: string;
  byline?: string;
  blurb: string;
  url?: string;
  topicSlugs?: string[];
  researcherSlugs?: string[];
  builds_on?: string[];
};

export const ERAS: Era[] = [
  {
    slug: "cybernetics",
    title: "Cybernetics & early neural",
    yearRange: [1943, 1956],
    short: "The first formal models of a neuron, the founding workshop, and the question that started it all.",
    blurb:
      "Before AI had a name, mathematicians and biologists tried to write down what a neuron does. McCulloch and Pitts gave it a calculus. Turing asked whether machines could think. Dartmouth named the field.",
    hue: "oklch(0.62 0.10 30)",
    themes: ["neuron models", "cybernetics", "Dartmouth", "Hebbian"],
  },
  {
    slug: "symbolic-ai",
    title: "Symbolic AI & first connectionists",
    yearRange: [1957, 1969],
    short: "Perceptron optimism, symbolic problem-solvers, and the book that froze a research programme.",
    blurb:
      "Two threads ran in parallel: Rosenblatt's perceptron made the first artificial neuron learn, and Newell & Simon built reasoning machines from symbols. Minsky and Papert ended the first wave of connectionism in print.",
    hue: "oklch(0.68 0.14 60)",
    themes: ["perceptron", "symbolic AI", "ELIZA", "GPS"],
  },
  {
    slug: "expert-systems",
    title: "AI winter & expert systems",
    yearRange: [1970, 1985],
    short: "The Lighthill report, MYCIN's medical knowledge, and Hopfield bringing neural ideas back from the cold.",
    blurb:
      "Funding froze on the symbolic side, but a parallel current kept neural ideas alive: Hopfield networks, Boltzmann machines, and the rules-engine successes of MYCIN and XCON kept the field employed.",
    hue: "oklch(0.65 0.10 90)",
    themes: ["AI winter", "expert systems", "Hopfield", "Boltzmann"],
  },
  {
    slug: "backprop-ml",
    title: "Backprop revival & statistical ML",
    yearRange: [1986, 2005],
    short: "The 1986 Nature paper, LeNet, SVMs, AdaBoost, random forests, LSTMs — two decades of foundations.",
    blurb:
      "Backprop became a household word. Vapnik's SVMs and Breiman's forests dominated competitions. LeCun's CNN read cheques. Hochreiter and Schmidhuber gave RNNs memory. The vocabulary of modern ML was set.",
    hue: "oklch(0.7 0.16 145)",
    themes: ["backprop", "SVM", "boosting", "LSTM"],
  },
  {
    slug: "deep-learning",
    title: "Deep learning revolution",
    yearRange: [2006, 2016],
    short: "Deep belief nets, ImageNet, AlexNet, Word2Vec, seq2seq, GANs, ResNet, attention, AlphaGo.",
    blurb:
      "Hinton showed deep nets could be trained. Krizhevsky and Sutskever crushed ImageNet. The era ran from a single Nature paper to AlphaGo defeating Lee Sedol in nine years.",
    hue: "oklch(0.68 0.18 200)",
    themes: ["AlexNet", "ResNet", "GAN", "AlphaGo"],
  },
  {
    slug: "foundation-models",
    title: "Transformers & foundation models",
    yearRange: [2017, 2022],
    short: "One paper rewrote the architecture. BERT, GPT, scaling laws, AlphaFold, CLIP, DALL·E, Codex, Chinchilla.",
    blurb:
      "Self-attention scaled with compute and data better than anything before it. By 2022 the transformer had spilled out of NLP into vision, biology, code, and image generation, and 'foundation model' became the standard term.",
    hue: "oklch(0.62 0.20 280)",
    themes: ["transformer", "scaling", "AlphaFold", "CLIP"],
  },
  {
    slug: "generative-explosion",
    title: "Generative explosion & alignment era",
    yearRange: [2022, 2024],
    short: "ChatGPT, Stable Diffusion, GPT-4, Llama, Claude, Gemini, Mixtral, DPO, Sora — and the alignment debate goes mainstream.",
    blurb:
      "Within eighteen months of ChatGPT, every major lab had a frontier model. Open weights from Meta, fast preference-tuning with DPO, and diffusion video crashed the gates. So did alignment, lawsuits, and the EU AI Act.",
    hue: "oklch(0.65 0.22 340)",
    themes: ["RLHF", "diffusion", "open weights", "alignment"],
  },
  {
    slug: "reasoning-agents",
    title: "Reasoning, agents & the post-LLM frontier",
    yearRange: [2024, 2026],
    short: "Test-time compute (o1/o3/R1), state-space models, mech-interp breakthroughs, MCP, agents, world models.",
    blurb:
      "Models started to think. OpenAI's o-series and DeepSeek-R1 traded inference compute for accuracy. Anthropic shipped MCP and scaled SAE interpretability. JEPA, Genie and AlphaProof pushed beyond next-token prediction.",
    hue: "oklch(0.70 0.18 195)",
    themes: ["reasoning", "agents", "interpretability", "world models"],
  },
];

export const ERA_BY_SLUG: Record<string, Era> = Object.fromEntries(
  ERAS.map((e) => [e.slug, e])
);

export const EVENTS: TimelineEvent[] = [
  // ════════════════ Cybernetics & early neural (1943-1956) ════════════════
  {
    id: "mcculloch-pitts-1943",
    year: 1943,
    era: "cybernetics",
    kind: "paper",
    title: "A logical calculus of the ideas immanent in nervous activity",
    byline: "McCulloch & Pitts",
    blurb:
      "The first mathematical model of a neuron. A network of binary threshold units can compute any logical function — the conceptual seed of every neural net since.",
    url: "https://www.cs.cmu.edu/~./epxing/Class/10715/reading/McCulloch.and.Pitts.pdf",
  },
  {
    id: "turing-1950",
    year: 1950,
    era: "cybernetics",
    kind: "paper",
    title: "Computing Machinery and Intelligence",
    byline: "Alan Turing",
    blurb:
      "'Can machines think?' Turing reframes the question as the imitation game and lays groundwork for both behaviorist evaluation and the moral horizon of the field.",
    url: "https://academic.oup.com/mind/article/LIX/236/433/986238",
    builds_on: ["mcculloch-pitts-1943"],
  },
  {
    id: "hebb-1949",
    year: 1949,
    era: "cybernetics",
    kind: "paper",
    title: "The Organization of Behavior",
    byline: "Donald Hebb",
    blurb:
      "Cells that fire together wire together. Hebbian learning becomes the canonical local rule and the ancestor of correlation-based weight updates.",
    builds_on: ["mcculloch-pitts-1943"],
  },
  {
    id: "shannon-1948",
    year: 1948,
    era: "cybernetics",
    kind: "paper",
    title: "A Mathematical Theory of Communication",
    byline: "Claude Shannon",
    blurb:
      "Information theory. Entropy, channel capacity, and mutual information — the language ML still uses for cross-entropy and KL divergence.",
    url: "https://people.math.harvard.edu/~ctm/home/text/others/shannon/entropy/entropy.pdf",
    topicSlugs: ["01-math/02-probability-information"],
    researcherSlugs: ["mackay"],
  },
  {
    id: "dartmouth-1956",
    year: 1956,
    month: 8,
    era: "cybernetics",
    kind: "milestone",
    title: "Dartmouth Summer Research Project",
    byline: "McCarthy, Minsky, Rochester, Shannon",
    blurb:
      "The proposal that named the field 'artificial intelligence' and gathered the people who'd run it for the next thirty years.",
    builds_on: ["turing-1950", "shannon-1948"],
  },

  // ════════════════ Symbolic AI & first connectionists (1957-1969) ════════════════
  {
    id: "perceptron-1958",
    year: 1958,
    era: "symbolic-ai",
    kind: "paper",
    title: "The Perceptron",
    byline: "Frank Rosenblatt",
    blurb:
      "A learnable linear classifier with a hardware implementation. Front-page news at the time and the prototype every later neural net inherits from.",
    builds_on: ["mcculloch-pitts-1943", "hebb-1949"],
  },
  {
    id: "lisp-1958",
    year: 1958,
    era: "symbolic-ai",
    kind: "milestone",
    title: "Lisp",
    byline: "John McCarthy",
    blurb:
      "The lingua franca of symbolic AI for thirty years — first-class functions, garbage collection, code-as-data.",
  },
  {
    id: "gps-1959",
    year: 1959,
    era: "symbolic-ai",
    kind: "system",
    title: "General Problem Solver",
    byline: "Newell, Simon, Shaw",
    blurb:
      "Means-ends analysis as a universal reasoner. The high-water mark of the symbolic dream of intelligence-as-search.",
  },
  {
    id: "eliza-1966",
    year: 1966,
    era: "symbolic-ai",
    kind: "system",
    title: "ELIZA",
    byline: "Joseph Weizenbaum",
    blurb:
      "A pattern-matching chatbot that fooled people into believing they were talking with a therapist. The first time the field grappled with anthropomorphism.",
  },
  {
    id: "shrdlu-1968",
    year: 1968,
    era: "symbolic-ai",
    kind: "system",
    title: "SHRDLU",
    byline: "Terry Winograd",
    blurb:
      "Natural-language understanding in a blocks world. Brilliant in its domain — and a cautionary tale about how toy results don't generalize.",
  },
  {
    id: "minsky-papert-1969",
    year: 1969,
    era: "symbolic-ai",
    kind: "controversy",
    title: "Perceptrons (book)",
    byline: "Minsky & Papert",
    blurb:
      "Showed single-layer perceptrons can't learn XOR. The book is more nuanced than the legend, but its publication coincided with a decade-long collapse of connectionist funding.",
    builds_on: ["perceptron-1958"],
  },

  // ════════════════ AI winter & expert systems (1970-1985) ════════════════
  {
    id: "lighthill-1973",
    year: 1973,
    era: "expert-systems",
    kind: "controversy",
    title: "Lighthill report",
    byline: "James Lighthill",
    blurb:
      "Commissioned by the UK Science Research Council. Concluded that AI had failed to deliver — triggered the first AI winter and defunding across Britain.",
  },
  {
    id: "mycin-1974",
    year: 1974,
    era: "expert-systems",
    kind: "system",
    title: "MYCIN",
    byline: "Shortliffe et al., Stanford",
    blurb:
      "A rule-based expert system that diagnosed bacterial infections better than many junior physicians. Birth of a commercial expert-systems wave.",
  },
  {
    id: "neocognitron-1980",
    year: 1980,
    era: "expert-systems",
    kind: "paper",
    title: "Neocognitron",
    byline: "Kunihiko Fukushima",
    blurb:
      "Hierarchical, locally-connected vision network with translation invariance. The architectural ancestor of every CNN.",
    topicSlugs: ["03-deep-learning/02-cnn"],
  },
  {
    id: "hopfield-1982",
    year: 1982,
    era: "expert-systems",
    kind: "paper",
    title: "Hopfield networks",
    byline: "John Hopfield",
    blurb:
      "Recurrent networks with energy functions and content-addressable memory. Reignited mainstream interest in neural computation.",
    builds_on: ["mcculloch-pitts-1943", "hebb-1949"],
  },
  {
    id: "boltzmann-1985",
    year: 1985,
    era: "expert-systems",
    kind: "paper",
    title: "Boltzmann machines",
    byline: "Hinton & Sejnowski",
    blurb:
      "Stochastic recurrent networks that learn by minimising free energy. The work cited in Hinton's 2024 Nobel Prize in Physics.",
    researcherSlugs: ["hinton"],
    builds_on: ["hopfield-1982"],
  },
  {
    id: "nettalk-1986",
    year: 1986,
    era: "expert-systems",
    kind: "system",
    title: "NETtalk",
    byline: "Sejnowski & Rosenberg",
    blurb:
      "A neural net that learned to pronounce English text aloud — a public demo that showed connectionism could do something useful.",
  },

  // ════════════════ Backprop revival & statistical ML (1986-2005) ════════════════
  {
    id: "backprop-1986",
    year: 1986,
    month: 10,
    era: "backprop-ml",
    kind: "paper",
    title: "Learning representations by back-propagating errors",
    byline: "Rumelhart, Hinton & Williams",
    blurb:
      "The Nature paper that made backprop the standard. Multilayer networks become trainable, and three decades of deep learning hinge on this method.",
    url: "https://www.nature.com/articles/323533a0",
    topicSlugs: ["03-deep-learning/01-mlp-backprop"],
    researcherSlugs: ["hinton"],
    builds_on: ["perceptron-1958"],
  },
  {
    id: "universal-approx-1989",
    year: 1989,
    era: "backprop-ml",
    kind: "paper",
    title: "Universal approximation theorem",
    byline: "Cybenko / Hornik",
    blurb:
      "A single hidden layer with enough units can approximate any continuous function. Provided theoretical license for the empirical race.",
    builds_on: ["backprop-1986"],
  },
  {
    id: "lenet-1989",
    year: 1989,
    era: "backprop-ml",
    kind: "model",
    title: "LeNet & convolutional networks",
    byline: "Yann LeCun",
    blurb:
      "First successful CNN, applied to handwritten digit recognition. Used by US banks to read cheques in the 1990s.",
    topicSlugs: ["03-deep-learning/02-cnn"],
    researcherSlugs: ["lecun"],
    builds_on: ["backprop-1986", "neocognitron-1980"],
  },
  {
    id: "qlearning-1989",
    year: 1989,
    era: "backprop-ml",
    kind: "paper",
    title: "Q-learning",
    byline: "Chris Watkins",
    blurb:
      "Off-policy temporal-difference learning. Decades later, Q-learning is still the conceptual core of deep RL.",
    topicSlugs: ["08-rl/02-q-learning"],
    researcherSlugs: ["sutton"],
  },
  {
    id: "td-gammon-1992",
    year: 1992,
    era: "backprop-ml",
    kind: "system",
    title: "TD-Gammon",
    byline: "Gerald Tesauro",
    blurb:
      "A self-play backgammon program that reached world-class play with TD(λ) — the proof of concept that deep RL inherited from.",
    builds_on: ["qlearning-1989"],
  },
  {
    id: "svm-1995",
    year: 1995,
    era: "backprop-ml",
    kind: "paper",
    title: "Support vector machines",
    byline: "Cortes & Vapnik",
    blurb:
      "Maximum-margin classifiers + the kernel trick. SVMs dominated benchmark leaderboards for a decade.",
    topicSlugs: ["02-classical-ml/02-svm"],
    researcherSlugs: ["vapnik", "scholkopf"],
  },
  {
    id: "lstm-1997",
    year: 1997,
    era: "backprop-ml",
    kind: "paper",
    title: "Long Short-Term Memory",
    byline: "Hochreiter & Schmidhuber",
    blurb:
      "Gated recurrent cells that solve the vanishing gradient problem. LSTMs powered NMT and speech recognition until transformers replaced them in 2017.",
    url: "https://www.bioinf.jku.at/publications/older/2604.pdf",
    topicSlugs: ["03-deep-learning/03-rnn-lstm"],
    researcherSlugs: ["hochreiter"],
  },
  {
    id: "deep-blue-1997",
    year: 1997,
    month: 5,
    era: "backprop-ml",
    kind: "milestone",
    title: "Deep Blue beats Kasparov",
    byline: "IBM",
    blurb:
      "Brute-force search and hand-engineered evaluation defeat the reigning world chess champion — a symbolic victory for symbolic AI.",
  },
  {
    id: "adaboost-1995",
    year: 1995,
    era: "backprop-ml",
    kind: "paper",
    title: "AdaBoost",
    byline: "Freund & Schapire",
    blurb:
      "Combine weak learners into a strong one by reweighting mistakes. Boosting becomes the dominant paradigm for tabular ML.",
    topicSlugs: ["02-classical-ml/03-trees-boosting"],
    researcherSlugs: ["freund"],
  },
  {
    id: "lecun-1998",
    year: 1998,
    era: "backprop-ml",
    kind: "paper",
    title: "Gradient-based learning applied to document recognition",
    byline: "LeCun, Bottou, Bengio, Haffner",
    blurb:
      "The canonical reference for LeNet-5 and the convolutional approach to image classification.",
    url: "http://yann.lecun.com/exdb/publis/pdf/lecun-98.pdf",
    researcherSlugs: ["lecun", "bengio"],
    builds_on: ["lenet-1989"],
  },
  {
    id: "pagerank-1998",
    year: 1998,
    era: "backprop-ml",
    kind: "paper",
    title: "PageRank",
    byline: "Page & Brin",
    blurb:
      "A graph algorithm for trustworthy search. Spawned Google, which would later spawn most of modern AI.",
  },
  {
    id: "random-forests-2001",
    year: 2001,
    era: "backprop-ml",
    kind: "paper",
    title: "Random Forests",
    byline: "Leo Breiman",
    blurb:
      "Bagging + decision trees + random feature subsets. Still the first thing many practitioners reach for on tabular data.",
    topicSlugs: ["02-classical-ml/03-trees-boosting"],
    researcherSlugs: ["breiman"],
  },
  {
    id: "two-cultures-2001",
    year: 2001,
    era: "backprop-ml",
    kind: "paper",
    title: "Statistical Modeling: The Two Cultures",
    byline: "Leo Breiman",
    blurb:
      "Breiman names the rift between data modelling and algorithmic modelling. The essay aged well.",
    researcherSlugs: ["breiman"],
  },

  // ════════════════ Deep learning revolution (2006-2016) ════════════════
  {
    id: "dbn-2006",
    year: 2006,
    era: "deep-learning",
    kind: "paper",
    title: "Deep belief nets & layer-wise pretraining",
    byline: "Hinton, Osindero & Teh",
    blurb:
      "RBM-based pretraining made deep networks trainable in practice. Coined the phrase 'deep learning' in popular use.",
    researcherSlugs: ["hinton"],
    builds_on: ["boltzmann-1985"],
  },
  {
    id: "imagenet-2009",
    year: 2009,
    era: "deep-learning",
    kind: "paper",
    title: "ImageNet",
    byline: "Fei-Fei Li et al.",
    blurb:
      "Fourteen million labelled images. The dataset and the annual challenge that made every modern vision result possible.",
    url: "https://www.image-net.org/",
    researcherSlugs: ["fei-fei"],
  },
  {
    id: "alexnet-2012",
    year: 2012,
    month: 9,
    era: "deep-learning",
    kind: "model",
    title: "AlexNet",
    byline: "Krizhevsky, Sutskever & Hinton",
    blurb:
      "GPU-trained 8-layer CNN that won ImageNet by a landslide. The match that lit the deep-learning rocket.",
    url: "https://papers.nips.cc/paper/4824-imagenet-classification-with-deep-convolutional-neural-networks",
    topicSlugs: ["03-deep-learning/02-cnn"],
    researcherSlugs: ["sutskever", "hinton"],
    builds_on: ["dbn-2006", "imagenet-2009", "lecun-1998"],
  },
  {
    id: "word2vec-2013",
    year: 2013,
    month: 1,
    era: "deep-learning",
    kind: "paper",
    title: "Word2Vec",
    byline: "Mikolov et al., Google",
    blurb:
      "Dense word embeddings learned from context. king − man + woman ≈ queen. Set the template for representation learning.",
  },
  {
    id: "dqn-2013",
    year: 2013,
    month: 12,
    era: "deep-learning",
    kind: "paper",
    title: "DQN: Playing Atari with deep RL",
    byline: "Mnih et al., DeepMind",
    blurb:
      "Q-learning + a CNN over raw pixels achieves human-level play on dozens of Atari games. Deep RL is born.",
    topicSlugs: ["08-rl/02-q-learning"],
    researcherSlugs: ["hassabis"],
    builds_on: ["qlearning-1989", "alexnet-2012"],
  },
  {
    id: "vae-2013",
    year: 2013,
    month: 12,
    era: "deep-learning",
    kind: "paper",
    title: "Variational autoencoder",
    byline: "Kingma & Welling",
    blurb:
      "Reparameterisation trick + ELBO objective makes deep generative latent-variable models trainable end-to-end.",
    url: "https://arxiv.org/abs/1312.6114",
    topicSlugs: ["07-generative-theory/01-vae"],
    researcherSlugs: ["kingma", "welling"],
  },
  {
    id: "gan-2014",
    year: 2014,
    month: 6,
    era: "deep-learning",
    kind: "paper",
    title: "Generative Adversarial Networks",
    byline: "Ian Goodfellow et al.",
    blurb:
      "Two networks fight: generator vs discriminator. Sparks a decade of generative image research culminating in StyleGAN.",
    url: "https://arxiv.org/abs/1406.2661",
    topicSlugs: ["07-generative-theory/02-gan"],
    researcherSlugs: ["goodfellow"],
  },
  {
    id: "seq2seq-2014",
    year: 2014,
    month: 9,
    era: "deep-learning",
    kind: "paper",
    title: "Sequence to sequence learning",
    byline: "Sutskever, Vinyals & Le",
    blurb:
      "Encoder-decoder LSTMs translate between languages with no hand-crafted features. Direct ancestor of the transformer.",
    url: "https://arxiv.org/abs/1409.3215",
    topicSlugs: ["03-deep-learning/03-rnn-lstm"],
    researcherSlugs: ["sutskever"],
    builds_on: ["lstm-1997"],
  },
  {
    id: "bahdanau-2014",
    year: 2014,
    month: 9,
    era: "deep-learning",
    kind: "paper",
    title: "Neural machine translation by jointly learning to align and translate",
    byline: "Bahdanau, Cho & Bengio",
    blurb:
      "Soft attention over encoder states fixes seq2seq's bottleneck. The mechanism the transformer would later run with.",
    url: "https://arxiv.org/abs/1409.0473",
    topicSlugs: ["03-deep-learning/04-attention"],
    researcherSlugs: ["bengio"],
    builds_on: ["seq2seq-2014"],
  },
  {
    id: "adam-2014",
    year: 2014,
    month: 12,
    era: "deep-learning",
    kind: "paper",
    title: "Adam optimizer",
    byline: "Kingma & Ba",
    blurb:
      "Adaptive per-parameter step sizes with momentum. Default optimizer for almost every deep model since.",
    url: "https://arxiv.org/abs/1412.6980",
    topicSlugs: ["01-math/03-optimization"],
    researcherSlugs: ["kingma"],
  },
  {
    id: "adversarial-examples-2014",
    year: 2014,
    month: 2,
    era: "deep-learning",
    kind: "paper",
    title: "Adversarial examples",
    byline: "Szegedy, Goodfellow et al.",
    blurb:
      "Imperceptible image perturbations cause confident mis-classifications. Robustness becomes its own subfield.",
    researcherSlugs: ["goodfellow", "madry"],
  },
  {
    id: "resnet-2015",
    year: 2015,
    month: 12,
    era: "deep-learning",
    kind: "paper",
    title: "Deep residual learning (ResNet)",
    byline: "Kaiming He et al.",
    blurb:
      "Skip connections let networks scale to 152 layers. The trick is now everywhere: transformers, U-Nets, diffusion models.",
    url: "https://arxiv.org/abs/1512.03385",
    topicSlugs: ["03-deep-learning/02-cnn"],
    researcherSlugs: ["he"],
    builds_on: ["alexnet-2012"],
  },
  {
    id: "alphago-2016",
    year: 2016,
    month: 3,
    era: "deep-learning",
    kind: "milestone",
    title: "AlphaGo defeats Lee Sedol",
    byline: "DeepMind",
    blurb:
      "MCTS + deep RL + self-play. The most-watched man-vs-machine match since Deep Blue, and a turning point for public perception.",
    url: "https://www.nature.com/articles/nature16961",
    topicSlugs: ["08-rl/05-alphago-zero"],
    researcherSlugs: ["silver", "hassabis"],
    builds_on: ["dqn-2013"],
  },
  {
    id: "tay-2016",
    year: 2016,
    month: 3,
    era: "deep-learning",
    kind: "controversy",
    title: "Microsoft Tay",
    byline: "Microsoft",
    blurb:
      "A Twitter chatbot was reduced to spouting racist filth within sixteen hours. Early lesson in deployment, prompt injection, and adversarial users.",
  },
  {
    id: "tpu-2016",
    year: 2016,
    month: 5,
    era: "deep-learning",
    kind: "system",
    title: "Google TPU",
    byline: "Google",
    blurb:
      "First custom silicon explicitly for neural network inference. Hardware-software co-design enters the AI era.",
    researcherSlugs: ["dean"],
  },
  {
    id: "wavenet-2016",
    year: 2016,
    month: 9,
    era: "deep-learning",
    kind: "paper",
    title: "WaveNet",
    byline: "DeepMind",
    blurb:
      "Dilated causal convolutions generate raw audio sample-by-sample. Powered Google Assistant's voice within a year.",
  },
  {
    id: "alphazero-2017",
    year: 2017,
    month: 12,
    era: "deep-learning",
    kind: "system",
    title: "AlphaZero",
    byline: "DeepMind",
    blurb:
      "Pure self-play, no human data. Same algorithm masters chess, shogi, and Go. The cleanest demonstration of self-play RL.",
    topicSlugs: ["08-rl/05-alphago-zero", "08-rl/06-mcts-game-playing"],
    researcherSlugs: ["silver", "hassabis"],
    builds_on: ["alphago-2016"],
  },

  // ════════════════ Transformers & foundation models (2017-2022) ════════════════
  {
    id: "transformer-2017",
    year: 2017,
    month: 6,
    era: "foundation-models",
    kind: "paper",
    title: "Attention Is All You Need",
    byline: "Vaswani et al., Google",
    blurb:
      "Drop the recurrence; keep self-attention. The transformer overtakes LSTMs on translation and goes on to eat the rest of ML.",
    url: "https://arxiv.org/abs/1706.03762",
    topicSlugs: ["03-deep-learning/04-attention"],
    researcherSlugs: ["vaswani", "shazeer"],
    builds_on: ["bahdanau-2014", "seq2seq-2014"],
  },
  {
    id: "moe-2017",
    year: 2017,
    era: "foundation-models",
    kind: "paper",
    title: "Outrageously large neural networks (sparsely-gated MoE)",
    byline: "Shazeer et al.",
    blurb:
      "Train trillion-parameter networks where each token only sees a small subset. Reborn five years later as Switch and Mixtral.",
    url: "https://arxiv.org/abs/1701.06538",
    topicSlugs: ["10-cutting-edge/01-moe"],
    researcherSlugs: ["shazeer"],
  },
  {
    id: "ppo-2017",
    year: 2017,
    month: 7,
    era: "foundation-models",
    kind: "paper",
    title: "Proximal Policy Optimization",
    byline: "John Schulman et al., OpenAI",
    blurb:
      "Clip the policy update; everyone uses this. PPO is the workhorse of deep RL and the engine of RLHF.",
    url: "https://arxiv.org/abs/1707.06347",
    topicSlugs: ["08-rl/03-policy-gradient-ppo"],
    researcherSlugs: ["schulman"],
  },
  {
    id: "gpt1-2018",
    year: 2018,
    month: 6,
    era: "foundation-models",
    kind: "model",
    title: "GPT-1",
    byline: "Radford et al., OpenAI",
    blurb:
      "Generative pretraining + task-specific fine-tuning. The first 'GPT' — small by today's standards but architecturally identical.",
    topicSlugs: ["04-transformers-llms/01-gpt"],
    researcherSlugs: ["radford"],
    builds_on: ["transformer-2017"],
  },
  {
    id: "bert-2018",
    year: 2018,
    month: 10,
    era: "foundation-models",
    kind: "model",
    title: "BERT",
    byline: "Devlin et al., Google",
    blurb:
      "Bidirectional encoder + masked language modelling. Smashed the GLUE benchmark and defined the encoder pretraining era.",
    url: "https://arxiv.org/abs/1810.04805",
    topicSlugs: ["04-transformers-llms/02-bert"],
    researcherSlugs: ["devlin"],
    builds_on: ["transformer-2017"],
  },
  {
    id: "alphafold1-2018",
    year: 2018,
    month: 12,
    era: "foundation-models",
    kind: "system",
    title: "AlphaFold 1",
    byline: "DeepMind",
    blurb:
      "Won CASP13 by a margin nobody had seen in protein structure prediction. The opening salvo for AI in biology.",
    researcherSlugs: ["hassabis"],
  },
  {
    id: "gpt2-2019",
    year: 2019,
    month: 2,
    era: "foundation-models",
    kind: "model",
    title: "GPT-2",
    byline: "Radford et al., OpenAI",
    blurb:
      "1.5B parameters that produced shockingly fluent text. OpenAI initially withheld the full weights — a first taste of the deployment debate.",
    topicSlugs: ["04-transformers-llms/01-gpt"],
    researcherSlugs: ["radford"],
    builds_on: ["gpt1-2018"],
  },
  {
    id: "gpt2-staged-release-2019",
    year: 2019,
    month: 2,
    era: "foundation-models",
    kind: "controversy",
    title: "GPT-2 staged release",
    byline: "OpenAI",
    blurb:
      "OpenAI's decision to release GPT-2 in stages, citing misuse risk, kicked off a multi-year debate about responsible disclosure of model weights.",
    builds_on: ["gpt2-2019"],
  },
  {
    id: "megatron-2019",
    year: 2019,
    month: 9,
    era: "foundation-models",
    kind: "paper",
    title: "Megatron-LM",
    byline: "Shoeybi et al., NVIDIA",
    blurb:
      "Tensor parallelism for billion-parameter transformers. Made multi-GPU training of LLMs an engineering reality.",
    url: "https://arxiv.org/abs/1909.08053",
    topicSlugs: ["09-training-infra/01-fsdp-zero-tp"],
    researcherSlugs: ["shoeybi"],
  },
  {
    id: "ddpm-2020",
    year: 2020,
    month: 6,
    era: "foundation-models",
    kind: "paper",
    title: "Denoising Diffusion Probabilistic Models",
    byline: "Jonathan Ho et al.",
    blurb:
      "Made diffusion practical for image generation. Reframes generation as iterated denoising and triggers the modern image-gen wave.",
    url: "https://arxiv.org/abs/2006.11239",
    topicSlugs: ["06-multimodal/03-diffusion-ddpm-sd"],
    researcherSlugs: ["ho"],
    builds_on: ["vae-2013"],
  },
  {
    id: "score-sde-2020",
    year: 2020,
    month: 11,
    era: "foundation-models",
    kind: "paper",
    title: "Score-based generative modeling through SDEs",
    byline: "Yang Song et al.",
    blurb:
      "Unified score matching and diffusion under a single SDE framework. The theoretical scaffolding behind modern diffusion.",
    url: "https://arxiv.org/abs/2011.13456",
    topicSlugs: ["07-generative-theory/04-energy-based-models"],
    researcherSlugs: ["song-yang"],
    builds_on: ["ddpm-2020"],
  },
  {
    id: "scaling-laws-2020",
    year: 2020,
    month: 1,
    era: "foundation-models",
    kind: "paper",
    title: "Scaling laws for neural language models",
    byline: "Kaplan et al., OpenAI",
    blurb:
      "Loss is a clean power law in compute, data, and parameters. The empirical foundation of the entire scaling era.",
    url: "https://arxiv.org/abs/2001.08361",
    topicSlugs: ["04-transformers-llms/03-scaling-laws"],
    researcherSlugs: ["kaplan"],
  },
  {
    id: "gpt3-2020",
    year: 2020,
    month: 5,
    era: "foundation-models",
    kind: "model",
    title: "GPT-3",
    byline: "Brown et al., OpenAI",
    blurb:
      "175B parameters. Few-shot in-context learning emerges as a phenomenon — kicking off the modern LLM era.",
    url: "https://arxiv.org/abs/2005.14165",
    topicSlugs: ["04-transformers-llms/01-gpt", "10-cutting-edge/04-in-context-learning"],
    researcherSlugs: ["brown"],
    builds_on: ["gpt2-2019", "scaling-laws-2020"],
  },
  {
    id: "rlhf-summarize-2020",
    year: 2020,
    month: 9,
    era: "foundation-models",
    kind: "paper",
    title: "Learning to summarise from human feedback",
    byline: "Stiennon et al., OpenAI",
    blurb:
      "RLHF beats supervised summarisation. The blueprint that becomes InstructGPT and ChatGPT.",
    url: "https://arxiv.org/abs/2009.01325",
    topicSlugs: ["08-rl/04-rlhf-dpo-grpo"],
    researcherSlugs: ["stiennon"],
    builds_on: ["ppo-2017"],
  },
  {
    id: "rag-2020",
    year: 2020,
    month: 5,
    era: "foundation-models",
    kind: "paper",
    title: "Retrieval-Augmented Generation",
    byline: "Lewis et al., FAIR",
    blurb:
      "Combine a parametric LLM with a non-parametric retriever. The original RAG and the seed of every search-grounded chatbot.",
    url: "https://arxiv.org/abs/2005.11401",
    topicSlugs: ["10-cutting-edge/05-rag-long-context"],
    researcherSlugs: ["lewis-rag"],
  },
  {
    id: "zero-2020",
    year: 2020,
    month: 5,
    era: "foundation-models",
    kind: "paper",
    title: "ZeRO & DeepSpeed",
    byline: "Rajbhandari et al., Microsoft",
    blurb:
      "Shard optimizer state, gradients, and parameters across GPUs. Made trillion-parameter training memory-feasible.",
    url: "https://arxiv.org/abs/1910.02054",
    topicSlugs: ["09-training-infra/01-fsdp-zero-tp"],
    researcherSlugs: ["rajbhandari"],
  },
  {
    id: "vit-2020",
    year: 2020,
    month: 10,
    era: "foundation-models",
    kind: "paper",
    title: "Vision Transformer (ViT)",
    byline: "Dosovitskiy et al., Google",
    blurb:
      "Patches as tokens, transformer as backbone. Vision models converge with language models.",
    builds_on: ["transformer-2017"],
  },
  {
    id: "clip-2021",
    year: 2021,
    month: 1,
    era: "foundation-models",
    kind: "paper",
    title: "CLIP",
    byline: "Radford et al., OpenAI",
    blurb:
      "Contrastive image–text pretraining. Zero-shot classification, the embedding backbone for DALL·E and Stable Diffusion.",
    url: "https://arxiv.org/abs/2103.00020",
    topicSlugs: ["06-multimodal/01-clip"],
    researcherSlugs: ["radford"],
    builds_on: ["transformer-2017"],
  },
  {
    id: "dalle-2021",
    year: 2021,
    month: 1,
    era: "foundation-models",
    kind: "model",
    title: "DALL·E",
    byline: "OpenAI",
    blurb:
      "Text → image with a discrete VAE + autoregressive transformer. The first viral text-to-image system.",
    builds_on: ["clip-2021", "vae-2013"],
  },
  {
    id: "lora-2021",
    year: 2021,
    month: 6,
    era: "foundation-models",
    kind: "paper",
    title: "LoRA",
    byline: "Edward Hu et al., Microsoft",
    blurb:
      "Low-rank adapters add trainable matrices to frozen weights. Made fine-tuning of huge LLMs accessible to non-frontier labs.",
    url: "https://arxiv.org/abs/2106.09685",
    topicSlugs: ["09-training-infra/02-lora-qlora"],
    researcherSlugs: ["hu"],
  },
  {
    id: "alphafold2-2021",
    year: 2021,
    month: 7,
    era: "foundation-models",
    kind: "system",
    title: "AlphaFold 2",
    byline: "Jumper et al., DeepMind",
    blurb:
      "Atomic-resolution structure prediction at competitive accuracy with experiments. Dropped 200M structures into the public PDB.",
    researcherSlugs: ["hassabis"],
    builds_on: ["alphafold1-2018", "transformer-2017"],
  },
  {
    id: "switch-2021",
    year: 2021,
    month: 1,
    era: "foundation-models",
    kind: "paper",
    title: "Switch Transformer",
    byline: "Fedus, Zoph & Shazeer",
    blurb:
      "Trillion-parameter sparsely-routed model. Made MoE training stable and ergonomic.",
    url: "https://arxiv.org/abs/2101.03961",
    topicSlugs: ["10-cutting-edge/01-moe"],
    researcherSlugs: ["fedus", "shazeer"],
    builds_on: ["moe-2017"],
  },
  {
    id: "codex-2021",
    year: 2021,
    month: 7,
    era: "foundation-models",
    kind: "model",
    title: "Codex & GitHub Copilot",
    byline: "OpenAI / GitHub",
    blurb:
      "GPT fine-tuned on code became the first AI tool to enter daily life for millions of developers.",
    builds_on: ["gpt3-2020"],
  },
  {
    id: "stable-diffusion-2022",
    year: 2022,
    month: 8,
    era: "foundation-models",
    kind: "model",
    title: "Stable Diffusion (Latent Diffusion)",
    byline: "Rombach et al.",
    blurb:
      "Diffusion in latent space, open weights. Image generation became something anyone could run on a consumer GPU.",
    url: "https://arxiv.org/abs/2112.10752",
    topicSlugs: ["06-multimodal/03-diffusion-ddpm-sd"],
    researcherSlugs: ["rombach"],
    builds_on: ["ddpm-2020", "clip-2021"],
  },
  {
    id: "instructgpt-2022",
    year: 2022,
    month: 1,
    era: "foundation-models",
    kind: "paper",
    title: "InstructGPT",
    byline: "Ouyang et al., OpenAI",
    blurb:
      "SFT + RLHF turn a base model into an aligned assistant. The recipe behind ChatGPT.",
    topicSlugs: ["04-transformers-llms/04-instruction-tuning", "08-rl/04-rlhf-dpo-grpo"],
    researcherSlugs: ["schulman"],
    builds_on: ["rlhf-summarize-2020", "gpt3-2020"],
  },
  {
    id: "cot-2022",
    year: 2022,
    month: 1,
    era: "foundation-models",
    kind: "paper",
    title: "Chain-of-thought prompting",
    byline: "Wei et al., Google",
    blurb:
      "'Let's think step by step.' Asking models to reason before answering unlocks new capability.",
    url: "https://arxiv.org/abs/2201.11903",
    topicSlugs: ["05-reasoning-agents/02-cot-react"],
    researcherSlugs: ["wei"],
  },
  {
    id: "emergent-2022",
    year: 2022,
    month: 6,
    era: "foundation-models",
    kind: "paper",
    title: "Emergent abilities of large language models",
    byline: "Wei et al.",
    blurb:
      "Some skills appear sharply at scale. Controversial methodology aside, the paper named a phenomenon that drove the next year of investment.",
    url: "https://arxiv.org/abs/2206.07682",
    topicSlugs: ["10-cutting-edge/04-in-context-learning"],
    researcherSlugs: ["wei"],
    builds_on: ["scaling-laws-2020"],
  },
  {
    id: "chinchilla-2022",
    year: 2022,
    month: 3,
    era: "foundation-models",
    kind: "paper",
    title: "Chinchilla",
    byline: "Hoffmann et al., DeepMind",
    blurb:
      "Compute-optimal models train on far more tokens than people had assumed. Reshaped budgets at every frontier lab.",
    url: "https://arxiv.org/abs/2203.15556",
    topicSlugs: ["04-transformers-llms/03-scaling-laws"],
    researcherSlugs: ["hoffmann"],
    builds_on: ["scaling-laws-2020"],
  },
  {
    id: "palm-2022",
    year: 2022,
    month: 4,
    era: "foundation-models",
    kind: "model",
    title: "PaLM",
    byline: "Google",
    blurb:
      "540B params trained on Pathways infrastructure. State-of-the-art on dozens of tasks; the moment Google publicly caught up.",
    researcherSlugs: ["dean"],
    builds_on: ["gpt3-2020"],
  },
  {
    id: "flashattention-2022",
    year: 2022,
    month: 5,
    era: "foundation-models",
    kind: "paper",
    title: "FlashAttention",
    byline: "Tri Dao et al.",
    blurb:
      "Reframe attention as IO-bound and fuse the kernel. 2-4× speedups with exact attention; the default kernel today.",
    url: "https://arxiv.org/abs/2205.14135",
    topicSlugs: ["09-training-infra/04-flashattn-vllm"],
    researcherSlugs: ["dao"],
  },
  {
    id: "alphacode-2022",
    year: 2022,
    month: 2,
    era: "foundation-models",
    kind: "system",
    title: "AlphaCode",
    byline: "DeepMind",
    blurb:
      "Competitive-programming-grade code generation. Showed that sampling many candidates + filtering is a real strategy.",
    researcherSlugs: ["hassabis"],
  },
  {
    id: "dalle2-2022",
    year: 2022,
    month: 4,
    era: "foundation-models",
    kind: "model",
    title: "DALL·E 2",
    byline: "OpenAI",
    blurb:
      "CLIP + diffusion gives photorealistic, prompt-faithful image synthesis. Triggered the wider AI-art moment.",
    builds_on: ["clip-2021", "ddpm-2020"],
  },
  {
    id: "midjourney-2022",
    year: 2022,
    month: 7,
    era: "foundation-models",
    kind: "company",
    title: "Midjourney v3",
    byline: "Midjourney",
    blurb:
      "A text-to-image service in a Discord bot built a $200M-revenue company on community taste alone.",
  },
  {
    id: "imagen-2022",
    year: 2022,
    month: 5,
    era: "foundation-models",
    kind: "model",
    title: "Imagen",
    byline: "Google Brain",
    blurb:
      "T5 text encoder + cascaded diffusion produces strikingly faithful text-to-image generation.",
  },
  {
    id: "whisper-2022",
    year: 2022,
    month: 9,
    era: "foundation-models",
    kind: "model",
    title: "Whisper",
    byline: "Radford et al., OpenAI",
    blurb:
      "Multilingual speech recognition trained on 680k hours from the web. Open weights — became the de facto STT model.",
    researcherSlugs: ["radford"],
  },

  // ════════════════ Generative explosion & alignment era (2022-2024) ════════════════
  {
    id: "chatgpt-2022",
    year: 2022,
    month: 11,
    era: "generative-explosion",
    kind: "milestone",
    title: "ChatGPT released",
    byline: "OpenAI",
    blurb:
      "A free chat UI in front of GPT-3.5 became the fastest product to 100M users. The moment AI went mainstream.",
    builds_on: ["instructgpt-2022", "gpt3-2020"],
  },
  {
    id: "flow-matching-2022",
    year: 2022,
    month: 10,
    era: "generative-explosion",
    kind: "paper",
    title: "Flow matching",
    byline: "Lipman et al.",
    blurb:
      "Train continuous-time generative models by matching vector fields directly. Cleaner than diffusion, often faster.",
    url: "https://arxiv.org/abs/2210.02747",
    topicSlugs: ["06-multimodal/04-flow-matching"],
    researcherSlugs: ["liphardt"],
    builds_on: ["score-sde-2020"],
  },
  {
    id: "rectified-flow-2022",
    year: 2022,
    month: 9,
    era: "generative-explosion",
    kind: "paper",
    title: "Rectified flow",
    byline: "Liu et al.",
    blurb:
      "Straighten the trajectories between noise and data. Enables 1-step generation in many regimes.",
    topicSlugs: ["06-multimodal/04-flow-matching"],
    researcherSlugs: ["liu-rectified"],
    builds_on: ["flow-matching-2022"],
  },
  {
    id: "consistency-models-2023",
    year: 2023,
    month: 3,
    era: "generative-explosion",
    kind: "paper",
    title: "Consistency models",
    byline: "Yang Song et al., OpenAI",
    blurb:
      "Distil a diffusion model into a one-step generator while keeping multi-step quality.",
    url: "https://arxiv.org/abs/2303.01469",
    researcherSlugs: ["song-yang"],
    builds_on: ["score-sde-2020"],
  },
  {
    id: "llama-2023",
    year: 2023,
    month: 2,
    era: "generative-explosion",
    kind: "model",
    title: "Llama 1 leak",
    byline: "Meta",
    blurb:
      "Meta released Llama to researchers; weights leaked within days. Lit the open-source LLM ecosystem on fire.",
  },
  {
    id: "alpaca-2023",
    year: 2023,
    month: 3,
    era: "generative-explosion",
    kind: "model",
    title: "Stanford Alpaca",
    byline: "Stanford CRFM",
    blurb:
      "Instruction-tune Llama-7B on $600 of synthetic data and get usable conversational behaviour. Sparked a thousand fine-tunes.",
    url: "https://crfm.stanford.edu/2023/03/13/alpaca.html",
    researcherSlugs: ["hashimoto"],
    builds_on: ["llama-2023"],
  },
  {
    id: "gpt4-2023",
    year: 2023,
    month: 3,
    era: "generative-explosion",
    kind: "model",
    title: "GPT-4",
    byline: "OpenAI",
    blurb:
      "Multimodal, much smaller hallucination rate than GPT-3.5, dominant on bar exams and benchmarks. Architecture and parameter count never disclosed.",
    builds_on: ["chatgpt-2022", "chinchilla-2022"],
  },
  {
    id: "claude1-2023",
    year: 2023,
    month: 3,
    era: "generative-explosion",
    kind: "model",
    title: "Claude",
    byline: "Anthropic",
    blurb:
      "Anthropic's first publicly released model. Constitutional AI as an alignment alternative to RLHF.",
    researcherSlugs: ["amodei"],
  },
  {
    id: "ai-pause-2023",
    year: 2023,
    month: 3,
    era: "generative-explosion",
    kind: "controversy",
    title: "Future of Life 'AI pause' open letter",
    byline: "Future of Life Institute",
    blurb:
      "Signed by Bengio, Musk, Wozniak and others, the letter called for a six-month pause on training models more capable than GPT-4.",
    researcherSlugs: ["bengio"],
  },
  {
    id: "qlora-2023",
    year: 2023,
    month: 5,
    era: "generative-explosion",
    kind: "paper",
    title: "QLoRA",
    byline: "Tim Dettmers et al.",
    blurb:
      "4-bit base + LoRA adapters lets you fine-tune a 65B model on a single 48GB GPU. Made big-model fine-tuning possible at home.",
    url: "https://arxiv.org/abs/2305.14314",
    topicSlugs: ["09-training-infra/02-lora-qlora", "09-training-infra/03-quantization"],
    researcherSlugs: ["dettmers"],
    builds_on: ["lora-2021"],
  },
  {
    id: "dpo-2023",
    year: 2023,
    month: 5,
    era: "generative-explosion",
    kind: "paper",
    title: "Direct Preference Optimization",
    byline: "Rafailov et al., Stanford",
    blurb:
      "Skip the reward model — fit the policy directly to preference data with a closed-form loss. RLHF without RL.",
    url: "https://arxiv.org/abs/2305.18290",
    topicSlugs: ["08-rl/04-rlhf-dpo-grpo"],
    researcherSlugs: ["rafailov"],
    builds_on: ["instructgpt-2022", "rlhf-summarize-2020"],
  },
  {
    id: "voyager-2023",
    year: 2023,
    month: 5,
    era: "generative-explosion",
    kind: "system",
    title: "Voyager",
    byline: "Jim Fan et al., NVIDIA",
    blurb:
      "An open-ended LLM agent that plays Minecraft, writes its own skills, and accumulates a library over weeks.",
    url: "https://arxiv.org/abs/2305.16291",
    researcherSlugs: ["fan-jim"],
    builds_on: ["gpt4-2023"],
  },
  {
    id: "vllm-2023",
    year: 2023,
    month: 9,
    era: "generative-explosion",
    kind: "system",
    title: "vLLM & PagedAttention",
    byline: "Woosuk Kwon et al., UC Berkeley",
    blurb:
      "Treat the KV cache like virtual memory. Open-source serving infrastructure that delivered order-of-magnitude throughput gains.",
    url: "https://arxiv.org/abs/2309.06180",
    topicSlugs: ["09-training-infra/04-flashattn-vllm"],
    researcherSlugs: ["kwon"],
  },
  {
    id: "llava-2023",
    year: 2023,
    month: 4,
    era: "generative-explosion",
    kind: "model",
    title: "LLaVA",
    byline: "Liu et al.",
    blurb:
      "Bolt a CLIP encoder onto an LLM and instruction-tune. The blueprint for the open VLM ecosystem.",
    url: "https://arxiv.org/abs/2304.08485",
    topicSlugs: ["06-multimodal/02-llava"],
    researcherSlugs: ["liu-llava"],
    builds_on: ["clip-2021"],
  },
  {
    id: "llama2-2023",
    year: 2023,
    month: 7,
    era: "generative-explosion",
    kind: "model",
    title: "Llama 2",
    byline: "Meta",
    blurb:
      "First major frontier-class model released for commercial use. Open weights start to challenge closed labs on benchmarks.",
    builds_on: ["llama-2023"],
  },
  {
    id: "mamba-2023",
    year: 2023,
    month: 12,
    era: "generative-explosion",
    kind: "paper",
    title: "Mamba",
    byline: "Albert Gu & Tri Dao",
    blurb:
      "Selective state-space models with linear-time scaling. The first real architectural challenger to the transformer in years.",
    url: "https://arxiv.org/abs/2312.00752",
    topicSlugs: ["10-cutting-edge/02-mamba-ssm"],
    researcherSlugs: ["gu", "dao"],
    builds_on: ["s4-2022", "transformer-2017"],
  },
  {
    id: "s4-2022",
    year: 2022,
    month: 4,
    era: "foundation-models",
    kind: "paper",
    title: "S4 (Structured State Spaces)",
    byline: "Albert Gu et al.",
    blurb:
      "HiPPO + diagonal-plus-low-rank parameterisation. The conceptual ancestor of Mamba.",
    url: "https://arxiv.org/abs/2111.00396",
    topicSlugs: ["10-cutting-edge/02-mamba-ssm"],
    researcherSlugs: ["gu"],
  },
  {
    id: "mixtral-2023",
    year: 2023,
    month: 12,
    era: "generative-explosion",
    kind: "model",
    title: "Mixtral 8×7B",
    byline: "Mistral AI",
    blurb:
      "Sparse mixture-of-experts with open weights. Beat Llama 2 70B with a fraction of the active parameters.",
    topicSlugs: ["10-cutting-edge/01-moe"],
    builds_on: ["switch-2021", "moe-2017"],
  },
  {
    id: "gemini-2023",
    year: 2023,
    month: 12,
    era: "generative-explosion",
    kind: "model",
    title: "Gemini 1",
    byline: "Google DeepMind",
    blurb:
      "First Google model trained from scratch as multimodal. Comes in Nano/Pro/Ultra sizes for phone-to-server deployment.",
    researcherSlugs: ["hassabis"],
  },
  {
    id: "diffusion-policy-2023",
    year: 2023,
    month: 3,
    era: "generative-explosion",
    kind: "paper",
    title: "Diffusion Policy",
    byline: "Cheng Chi et al.",
    blurb:
      "Action prediction as denoising. Made diffusion the dominant approach for visuomotor robot control.",
    url: "https://arxiv.org/abs/2303.04137",
    researcherSlugs: ["chi-cheng"],
    builds_on: ["ddpm-2020"],
  },
  {
    id: "hyena-2023",
    year: 2023,
    month: 3,
    era: "generative-explosion",
    kind: "paper",
    title: "Hyena Hierarchy",
    byline: "Poli et al.",
    blurb:
      "Implicit-convolution alternative to attention with subquadratic scaling. A parallel branch of the post-transformer search.",
    url: "https://arxiv.org/abs/2302.10866",
    topicSlugs: ["11-niche-pivotal/03-hyena"],
    researcherSlugs: ["poli", "dao"],
  },
  {
    id: "i-jepa-2023",
    year: 2023,
    month: 1,
    era: "generative-explosion",
    kind: "paper",
    title: "I-JEPA",
    byline: "Assran et al., Meta",
    blurb:
      "Joint-embedding predictive architecture for images. LeCun's bet on representation prediction over pixel reconstruction starts shipping.",
    url: "https://arxiv.org/abs/2301.08243",
    topicSlugs: ["11-niche-pivotal/06-jepa"],
    researcherSlugs: ["assran", "lecun"],
  },
  {
    id: "claude2-2023",
    year: 2023,
    month: 7,
    era: "generative-explosion",
    kind: "model",
    title: "Claude 2",
    byline: "Anthropic",
    blurb:
      "100k-token context window, more capable code and reasoning. Set the bar for long-context.",
    researcherSlugs: ["amodei"],
  },
  {
    id: "perplexity-2022",
    year: 2022,
    month: 12,
    era: "generative-explosion",
    kind: "company",
    title: "Perplexity launch",
    byline: "Perplexity AI",
    blurb:
      "Conversational search with citations. Re-popularised RAG as a consumer product.",
    researcherSlugs: ["srinivas"],
  },
  {
    id: "claude3-2024",
    year: 2024,
    month: 3,
    era: "generative-explosion",
    kind: "model",
    title: "Claude 3 (Opus, Sonnet, Haiku)",
    byline: "Anthropic",
    blurb:
      "Anthropic's first family at GPT-4 quality. Opus matched or exceeded GPT-4 on most benchmarks at release.",
    researcherSlugs: ["amodei"],
    builds_on: ["claude2-2023"],
  },
  {
    id: "anthropic-saes-2024",
    year: 2024,
    month: 5,
    era: "generative-explosion",
    kind: "paper",
    title: "Scaling sparse autoencoders to Claude",
    byline: "Anthropic",
    blurb:
      "Extracted millions of monosemantic features from a frontier model. Mechanistic interpretability hits production scale.",
    topicSlugs: ["10-cutting-edge/03-mech-interp-saes"],
    researcherSlugs: ["olah", "nanda"],
  },
  {
    id: "llama3-2024",
    year: 2024,
    month: 4,
    era: "generative-explosion",
    kind: "model",
    title: "Llama 3",
    byline: "Meta",
    blurb:
      "8B and 70B with 15T training tokens. 405B followed in July. Open weights at frontier scale.",
    builds_on: ["llama2-2023", "chinchilla-2022"],
  },
  {
    id: "gpt4o-2024",
    year: 2024,
    month: 5,
    era: "generative-explosion",
    kind: "model",
    title: "GPT-4o",
    byline: "OpenAI",
    blurb:
      "Natively multimodal speech-vision-text in a single model. Real-time voice mode set a new bar for conversational AI.",
    researcherSlugs: ["fedus", "murati"],
    builds_on: ["gpt4-2023"],
  },
  {
    id: "claude35-sonnet-2024",
    year: 2024,
    month: 6,
    era: "generative-explosion",
    kind: "model",
    title: "Claude 3.5 Sonnet",
    byline: "Anthropic",
    blurb:
      "Mid-tier model that beat Opus on most benchmarks. Tool use and code became reliable enough for daily agent workflows.",
    researcherSlugs: ["amodei"],
    builds_on: ["claude3-2024"],
  },
  {
    id: "alphaproof-2024",
    year: 2024,
    month: 7,
    era: "generative-explosion",
    kind: "milestone",
    title: "AlphaProof & AlphaGeometry win IMO Silver",
    byline: "DeepMind",
    blurb:
      "Formal-math + RL system solves four of six International Math Olympiad problems at silver-medal level.",
    researcherSlugs: ["hassabis"],
    builds_on: ["alphazero-2017"],
  },
  {
    id: "veo-2024",
    year: 2024,
    month: 5,
    era: "generative-explosion",
    kind: "model",
    title: "Veo",
    byline: "Google DeepMind",
    blurb:
      "Minute-long, 1080p text-to-video. The video gen race goes multi-frontier.",
    topicSlugs: ["06-multimodal/05-video-sora-veo"],
    builds_on: ["sora-2024"],
  },
  {
    id: "sora-2024",
    year: 2024,
    month: 2,
    era: "generative-explosion",
    kind: "model",
    title: "Sora",
    byline: "OpenAI",
    blurb:
      "Diffusion transformer for minute-long video. Generated clips that became impossible to distinguish from real footage at thumbnail size.",
    topicSlugs: ["06-multimodal/05-video-sora-veo"],
    builds_on: ["stable-diffusion-2022", "transformer-2017"],
  },
  {
    id: "eu-ai-act-2024",
    year: 2024,
    month: 3,
    era: "generative-explosion",
    kind: "controversy",
    title: "EU AI Act",
    byline: "European Parliament",
    blurb:
      "First major regulatory framework for AI: tiered risk, transparency requirements for general-purpose models, fines up to 7% of revenue.",
  },

  // ════════════════ Reasoning, agents, and post-LLM frontier (2024-2026) ════════════════
  {
    id: "o1-preview-2024",
    year: 2024,
    month: 9,
    era: "reasoning-agents",
    kind: "model",
    title: "o1-preview",
    byline: "OpenAI",
    blurb:
      "First publicly available reasoning model. Trades inference compute for chain-of-thought quality and dramatically improved math/code.",
    topicSlugs: ["05-reasoning-agents/01-o1-o3-r1", "10-cutting-edge/08-test-time-compute"],
    researcherSlugs: ["sutskever"],
    builds_on: ["cot-2022", "alphazero-2017"],
  },
  {
    id: "sb1047-veto-2024",
    year: 2024,
    month: 9,
    era: "reasoning-agents",
    kind: "controversy",
    title: "California SB-1047 vetoed",
    byline: "Governor Newsom",
    blurb:
      "California's frontier-model safety bill was vetoed after intense industry lobbying. Set the political tone for US AI regulation.",
  },
  {
    id: "mcp-2024",
    year: 2024,
    month: 11,
    era: "reasoning-agents",
    kind: "system",
    title: "Model Context Protocol",
    byline: "Anthropic",
    blurb:
      "Open standard for connecting LLMs to tools and data. Claude, Cursor, Zed and more shipped MCP within months.",
    topicSlugs: ["05-reasoning-agents/03-mcp-agent-frameworks", "05-reasoning-agents/04-claude-skills-mcp-deep-dive"],
    researcherSlugs: ["amodei"],
  },
  {
    id: "deepseek-v3-2024",
    year: 2024,
    month: 12,
    era: "reasoning-agents",
    kind: "model",
    title: "DeepSeek-V3",
    byline: "DeepSeek",
    blurb:
      "671B-parameter MoE trained on a fraction of the budget of US labs. Open weights with frontier-class reasoning.",
    topicSlugs: ["10-cutting-edge/01-moe"],
    researcherSlugs: ["wenfeng"],
    builds_on: ["mixtral-2023"],
  },
  {
    id: "o1-2024",
    year: 2024,
    month: 12,
    era: "reasoning-agents",
    kind: "model",
    title: "o1",
    byline: "OpenAI",
    blurb:
      "Production reasoning model. PhD-level science benchmarks; the start of pricing models by tokens-of-thought.",
    topicSlugs: ["05-reasoning-agents/01-o1-o3-r1"],
    researcherSlugs: ["sutskever"],
    builds_on: ["o1-preview-2024"],
  },
  {
    id: "genie-2024",
    year: 2024,
    month: 12,
    era: "reasoning-agents",
    kind: "model",
    title: "Genie 2",
    byline: "Google DeepMind",
    blurb:
      "Foundation world model that turns a single image into an interactive 3D environment. World-model research goes generative.",
    topicSlugs: ["11-niche-pivotal/07-world-models"],
    researcherSlugs: ["hassabis"],
  },
  {
    id: "deepseek-r1-2025",
    year: 2025,
    month: 1,
    era: "reasoning-agents",
    kind: "model",
    title: "DeepSeek-R1",
    byline: "DeepSeek",
    blurb:
      "Open-weight reasoning model trained with GRPO and a cold-start distillation pipeline. Sparked a Western policy reaction in days.",
    url: "https://arxiv.org/abs/2501.12948",
    topicSlugs: ["05-reasoning-agents/01-o1-o3-r1", "08-rl/04-rlhf-dpo-grpo"],
    researcherSlugs: ["wenfeng"],
    builds_on: ["deepseek-v3-2024", "o1-2024", "ppo-2017"],
  },
  {
    id: "qwen-2025",
    year: 2025,
    month: 1,
    era: "reasoning-agents",
    kind: "model",
    title: "Qwen 2.5 family",
    byline: "Alibaba",
    blurb:
      "Open-weight Chinese frontier models including 72B dense and 32B reasoning. Made tri-polar (US/China/open) the new map.",
  },
  {
    id: "claude37-2025",
    year: 2025,
    month: 2,
    era: "reasoning-agents",
    kind: "model",
    title: "Claude 3.7 Sonnet (extended thinking)",
    byline: "Anthropic",
    blurb:
      "First hybrid model with optional extended-thinking mode. Same model, two inference modes — instant or reasoned.",
    researcherSlugs: ["amodei"],
    builds_on: ["claude35-sonnet-2024", "o1-2024"],
  },
  {
    id: "o3-2025",
    year: 2025,
    month: 4,
    era: "reasoning-agents",
    kind: "model",
    title: "o3",
    byline: "OpenAI",
    blurb:
      "Successor to o1 with major gains on ARC-AGI and Frontier Math. Reasoning-as-product becomes the default frontier offering.",
    topicSlugs: ["05-reasoning-agents/01-o1-o3-r1"],
    builds_on: ["o1-2024"],
  },
  {
    id: "veo3-2025",
    year: 2025,
    month: 5,
    era: "reasoning-agents",
    kind: "model",
    title: "Veo 3",
    byline: "Google DeepMind",
    blurb:
      "Synchronised audio + video generation; 4K minute-long clips. The text-to-video benchmark of mid-2025.",
    topicSlugs: ["06-multimodal/05-video-sora-veo"],
    builds_on: ["veo-2024"],
  },
  {
    id: "vjepa2-2025",
    year: 2025,
    month: 6,
    era: "reasoning-agents",
    kind: "paper",
    title: "V-JEPA 2",
    byline: "Meta FAIR",
    blurb:
      "Video-trained world model that does action-conditioned prediction in latent space. The strongest non-generative world model yet.",
    topicSlugs: ["11-niche-pivotal/06-jepa", "11-niche-pivotal/07-world-models"],
    researcherSlugs: ["assran", "lecun"],
    builds_on: ["i-jepa-2023"],
  },
  {
    id: "gemini25-2025",
    year: 2025,
    month: 3,
    era: "reasoning-agents",
    kind: "model",
    title: "Gemini 2.5 Pro",
    byline: "Google DeepMind",
    blurb:
      "Gemini's first reasoning-tuned release. Native 2M-token context and competitive on math/code.",
    researcherSlugs: ["hassabis"],
    builds_on: ["gemini-2023"],
  },
  {
    id: "claude4-2025",
    year: 2025,
    month: 5,
    era: "reasoning-agents",
    kind: "model",
    title: "Claude 4 (Sonnet & Opus)",
    byline: "Anthropic",
    blurb:
      "Pushed agentic coding to multi-hour autonomous tasks. SWE-bench leaderboards rewritten.",
    researcherSlugs: ["amodei"],
    builds_on: ["claude37-2025"],
  },
  {
    id: "llama33-2025",
    year: 2025,
    month: 1,
    era: "reasoning-agents",
    kind: "model",
    title: "Llama 3.3",
    byline: "Meta",
    blurb:
      "70B that matches the 405B from six months earlier. Distillation and post-training compress capability fast.",
    builds_on: ["llama3-2024"],
  },
  {
    id: "gpt45-2025",
    year: 2025,
    month: 2,
    era: "reasoning-agents",
    kind: "model",
    title: "GPT-4.5",
    byline: "OpenAI",
    blurb:
      "Last of the pure-pretraining flagships before OpenAI consolidated on the o-series.",
    builds_on: ["gpt4o-2024"],
  },
  {
    id: "claude-skills-2025",
    year: 2025,
    month: 9,
    era: "reasoning-agents",
    kind: "system",
    title: "Claude Skills",
    byline: "Anthropic",
    blurb:
      "Composable skills + MCP servers turn Claude into a programmable agent platform.",
    topicSlugs: ["05-reasoning-agents/04-claude-skills-mcp-deep-dive"],
    researcherSlugs: ["amodei"],
    builds_on: ["mcp-2024"],
  },
  {
    id: "openai-apps-2025",
    year: 2025,
    month: 10,
    era: "reasoning-agents",
    kind: "system",
    title: "OpenAI Apps",
    byline: "OpenAI",
    blurb:
      "Agentic apps inside ChatGPT with native tool integration — the consumer mirror of MCP-style architectures.",
  },
  {
    id: "gpt5-2025",
    year: 2025,
    month: 8,
    era: "reasoning-agents",
    kind: "model",
    title: "GPT-5",
    byline: "OpenAI",
    blurb:
      "Unified reasoning + non-reasoning frontier model. Routing decides per-query whether to think.",
    builds_on: ["o3-2025", "gpt45-2025"],
  },
  {
    id: "claude45-2025",
    year: 2025,
    month: 9,
    era: "reasoning-agents",
    kind: "model",
    title: "Claude Sonnet 4.5",
    byline: "Anthropic",
    blurb:
      "Specifically tuned for agents and computer use. Multi-day autonomous task runs become demoable.",
    researcherSlugs: ["amodei"],
    builds_on: ["claude4-2025"],
  },
  {
    id: "claude47-2026",
    year: 2026,
    month: 1,
    era: "reasoning-agents",
    kind: "model",
    title: "Claude Opus 4.7",
    byline: "Anthropic",
    blurb:
      "Million-token context with strong long-form reasoning, default for agentic IDE workflows.",
    researcherSlugs: ["amodei"],
    builds_on: ["claude45-2025"],
  },
  {
    id: "mech-interp-circuits-2025",
    year: 2025,
    month: 3,
    era: "reasoning-agents",
    kind: "paper",
    title: "Cross-layer transcoders & circuit tracing",
    byline: "Anthropic",
    blurb:
      "Made full computational traces of small Claude responses possible — interpretability scales beyond single-feature analysis.",
    topicSlugs: ["10-cutting-edge/03-mech-interp-saes"],
    researcherSlugs: ["olah", "nanda"],
    builds_on: ["anthropic-saes-2024"],
  },
  {
    id: "alphaevolve-2025",
    year: 2025,
    month: 5,
    era: "reasoning-agents",
    kind: "system",
    title: "AlphaEvolve",
    byline: "DeepMind",
    blurb:
      "LLM-driven evolutionary search discovers new fast matrix-multiplication algorithms and chip-design optimisations.",
    researcherSlugs: ["hassabis"],
    builds_on: ["alphaproof-2024"],
  },
];

export const EVENT_BY_ID: Record<string, TimelineEvent> = Object.fromEntries(
  EVENTS.map((e) => [e.id, e])
);

export function eventsByEra(eraSlug: string): TimelineEvent[] {
  return EVENTS.filter((e) => e.era === eraSlug).sort((a, b) => {
    if (a.year !== b.year) return a.year - b.year;
    return (a.month ?? 0) - (b.month ?? 0);
  });
}

export const TIMELINE_RANGE: [number, number] = [
  Math.min(...EVENTS.map((e) => e.year)),
  Math.max(...EVENTS.map((e) => e.year)),
];
